ceph/ceph-cm-ansible

- puddle.yml
- roles/puddle/defaults/main.yml
- roles/puddle/handlers/main.yml
- roles/puddle/meta/main.yml
- roles/puddle/tasks/configure.yml
- roles/puddle/tasks/distill/configure.yml
- roles/puddle/tasks/distill/install.yml
- roles/puddle/tasks/install.yml
- roles/puddle/tasks/main.yml
- roles/puddle/tasks/nfs.yml
- roles/puddle/tasks/nginx.yml
- roles/puddle/templates/ceph-1.2-rhel-6.conf
- roles/puddle/templates/ceph-1.2-rhel-7.conf
- roles/puddle/templates/ceph-1.3-rhel-7.conf
- roles/puddle/templates/distill/ceph-1.3-rhel-7.conf
- roles/puddle/templates/distill/ceph-distill
- roles/puddle/templates/distill/comps-ceph-1.3-rhel-7.xml
- roles/puddle/templates/distill/run-distill.conf
- roles/puddle/templates/distill/variants-ceph-1.3-rhel-7.xml
- roles/puddle/templates/eng-rhel-7.repo
- roles/puddle/templates/faucet.conf
- roles/puddle/templates/nginx.conf
- roles/puddle/templates/rcm-kerberos.conf
- roles/puddle/templates/rh-common-rhel-6.conf
- roles/puddle/templates/rh-common-rhel-7.conf
Add the necessary configuration for installing and running distill and puddle.
Many of the templated variables here are internal to Red Hat and are present in the other "secrets" Ansible repository.
> add puddle role and playbook

- roles/puddle/defaults/main.yml
- roles/puddle/tasks/main.yml
Adds some defaults for the puddle and distill hashes, as well as adding a couple tags.
> Puddle updates

- roles/testnode/tasks/apt_systems.yml
- roles/testnode/tasks/cpan.yml
- roles/testnode/tasks/redhat/rhel_7.0.yml
- roles/testnode/tasks/setup-debian.yml
This should should allow us to run --check with the testnodes.yml playbook now.
> More fixes to support --check mode.

- roles/ansible-managed/tasks/main.yml
- roles/cobbler/templates/snippets/cephlab_user
> Use a UID of 1100 for ansible_user

- roles/ansible-managed/tasks/main.yml
> Use  ansible_user_uid_ in ansible-managed role

- roles/ansible-managed/tasks/main.yml
So we can run with e.g. ``--tags="user,pubkeys"``
> pubkeys and user tags

- roles/cobbler/templates/kickstarts/cephlab_rhel.ks
> Use SELinux permissive on RHEL

- roles/testnode/vars/centos_6.yml
- roles/testnode/vars/centos_7.yml
- roles/testnode/vars/fedora_20.yml
- roles/testnode/vars/redhat_6.yml
- roles/testnode/vars/redhat_7.yml
> Make sure git is installed

- roles/users/tasks/main.yml
> 'user' tag, not 'users'

- cobbler.yml
- roles/cobbler/defaults/main.yml
- roles/cobbler/tasks/distro_prep.yml
- roles/cobbler/tasks/main.yml
- roles/cobbler_profile/defaults/main.yml
- roles/cobbler_profile/tasks/download_iso.yml
- roles/cobbler_profile/tasks/import_distro.yml
- roles/cobbler_profile/tasks/main.yml
> Add cobbler_role profile

- tools/vmlist.py
> Add tools subdir containing vmlist.py script

- roles/cobbler/templates/triggers/install/post/cephlab_ansible.sh
> Don't block while running the larger playbook

- roles/cobbler/templates/snippets/cephlab_rc_local
> Don't hit the post-install trigger multiple times

- roles/testnode/files/scripts/kernel_logging.sh
https://github.com/ceph/ceph-qa-chef/commit/22c21baafa562bd003d5a3102d44afdcf1d97a5b
> Port serial console grub work

- roles/cobbler/tasks/fetch_cm_repos.yml
- roles/cobbler/tasks/main.yml
These are used by cobbler after reimaging
> Manage CM repos in cobbler role

- roles/testnode/tasks/setup-ubuntu.yml
So that we can easily run just those actions against testnodes
> Add kernel_logging tag

- roles/cobbler/templates/snippets/cephlab_rhel_disks
http://tracker.ceph.com/issues/11825
> Use all of /dev/sda for /

- roles/testnode/files/scripts/kernel_logging.sh
> Fix typo in kernel_logging.sh

- roles/testnode/tasks/redhat/rhel_7.yml
- roles/testnode/tasks/redhat/set_hostname.yml
- roles/testnode/tasks/setup-redhat.yml
Fix them if they are 'localhost' as well.
> Also correct hostnames on RHEL6

- roles/ansible-managed/tasks/main.yml
- roles/cobbler/defaults/main.yml
- roles/cobbler/templates/snippets/cephlab_user
> Change 'ssh_keys' to 'ansible_user_ssh_keys' to clarify usage

- roles/common/tasks/rhel-entitlements.yml
If entitlements.yml is not found, don't attempt to register
> Gracefully skip registration

- roles/testnode/tasks/yum/packages.yml
https://bugzilla.redhat.com/show_bug.cgi?id=1234967
> Work around BZ#1234967

- roles/testnode/tasks/yum/packages.yml
> Remove saved yum transactions

- roles/ansible-managed/tasks/main.yml
> Skip ansible_user creation if it is undefined

- roles/cobbler/defaults/main.yml
- roles/cobbler/tasks/upload_templates.yml
- roles/cobbler/templates/httpd/index.html
> Help users locate cobbler's web UI

- roles/testnode/defaults/main.yml
- roles/testnode/tasks/apt_systems.yml
http://tracker.ceph.com/issues/12250
> implement modify_fstab to skip /etc/fstab modification

- README.rst
As always, grammar nazis welcome and appreciated.
> docs: explain where to define variables for use in roles

- roles/cobbler/tasks/redhat/rhel_7.yml
> Cobbler: ignore firewalld if it's not running

- roles/cobbler_systems/tasks/populate_systems.yml
For interface and kernel_options
> cobbler_systems: properly find defaults

- roles/cobbler/vars/apt_systems.yml
- roles/cobbler/vars/yum_systems.yml
> cobbler: install git

- roles/testnode/tasks/yum/packages.yml
- roles/testnode/vars/centos_7.yml
See: http://tracker.ceph.com/issues/12381
> testnode: add dbench and bonnie++ for centos7

- roles/common/tasks/main.yml
I think this will help with debugging.
> Common: Log the OS/version of each node

- roles/cobbler/defaults/main.yml
- roles/cobbler/templates/triggers/install/post/cephlab_ansible.sh
> Cobbler: update CM repos before running ansible

- roles/users/README.rst
- roles/users/defaults/main.yml
- roles/users/tasks/main.yml
> Add the ability to revoke user accounts

- roles/testnode/vars/centos_7.yml
Fixes: #12658
Signed-off-by: John Spray <john.spray@redhat.com>
> roles: add xfsprogs-devel for centos7

- roles/testnode/README.rst
- roles/testnode/defaults/main.yml
- roles/testnode/tasks/apt/packages.yml
- roles/testnode/tasks/yum/packages.yml
- roles/testnode/vars/apt_systems.yml
- roles/testnode/vars/yum_systems.yml
I just forgot to document this the last time around.
> tesnode: add `ceph_packages` to the README

- roles/testnode/tasks/user.yml
Fixes: http://tracker.ceph.com/issues/12670
> testnode: make teuthology_user passwordless

- roles/testnode/tasks/apt/repos.yml
http://tracker.ceph.com/issues/12794
> testnodes: Check for and remove custom apt repos

- roles/testnode/files/libexec/smart.pl
> smart.pl multiline mode: show failed/missing drives as well

- pulpito.yml
> Adds the pulpito playbook

- cobbler.yml
- roles/cobbler/defaults/main.yml
- roles/cobbler/tasks/distro_prep.yml
- roles/cobbler/tasks/main.yml
- roles/cobbler_profile/defaults/main.yml
- roles/cobbler_profile/tasks/download_image.yml
- roles/cobbler_profile/tasks/import_distro.yml
- roles/cobbler_profile/tasks/import_distro_image.yml
- roles/cobbler_profile/tasks/import_distro_iso.yml
http://tracker.ceph.com/issues/13063
> cobbler_profile: add non-iso image support and inktank-rescue

- roles/testnode/files/libexec/smart.pl
Adds support for magnas / non-raid systems
Adds support for nagios multiline output
Signed-off-by: dgalloway <dgallowa@REDHAT.COM>
> Updates to nagios disk monitoring script

- roles/teuthology/tasks/main.yml
- roles/teuthology/tasks/setup_log_access.yml
- roles/teuthology/tasks/setup_users.yml
- roles/teuthology/templates/nginx.conf
- roles/teuthology/templates/teuthology.yaml
- roles/teuthology/vars/apt_systems.yml
> teuthology: Serve logs over http

- cobbler.yml
- roles/cobbler_profile/defaults/main.yml
> Add dummy dban-2.3.0 entry

- roles/ansible-managed/tasks/main.yml
- roles/users/tasks/main.yml
> Don't attempt to add groups that don't exist

- roles/paddles/templates/prod.py
Fixes a bug introduced by:
https://github.com/pecan/pecan/commit/b14f4aa1682b77681a760ed948f8972a4e0d7d2a
> paddles: Update prod.py

- roles/testnode/vars/ubuntu_14.yml
http://tracker.ceph.com/issues/13572
> Temporarily disable blkin repo

- roles/teuthology/templates/teuthology.yaml
> Allow setting max job time for teuthology

- roles/cobbler_systems/tasks/populate_systems.yml
Ran across this and remembered someone saying, at some point, "seems like something we should set in ansible."
> Set hostname in cobbler system profiles

- cobbler.yml
- roles/cobbler_profile/defaults/main.yml
> Add RHEL 7.2

- packages.yml
- roles/packages/README.rst
- roles/packages/defaults/main.yml
- roles/packages/tasks/cleanup.yml
- roles/packages/tasks/main.yml
- roles/packages/tasks/packages.yml
- roles/packages/tasks/setup.yml
See: http://tracker.ceph.com/issues/13851
> A new playbook to install or remove packages

- roles/testnode/tasks/resolvconf.yml
> testnode: Handle interfaces stanzas with leading whitespace

- roles/testnode/tasks/drive_partitioning.yml
- roles/testnode/tasks/main.yml
> Add task to partition extra drives (like on smithi)

- tools/vmlist.py
> vmlist.py: vercoi is no more

- roles/testnode/vars/centos_6.yml
- roles/testnode/vars/centos_7.yml
- roles/testnode/vars/debian_7.yml
- roles/testnode/vars/debian_8.yml
- roles/testnode/vars/fedora_20.yml
- roles/testnode/vars/ubuntu.yml
Reverts ceph/ceph-cm-ansible#176
> Revert "Disable fastcgi repos and package installs"

- roles/testnode/vars/centos_6.yml
- roles/testnode/vars/centos_7.yml
- roles/testnode/vars/redhat_6.yml
- roles/testnode/vars/redhat_7.yml
Reverts ceph/ceph-cm-ansible#177
> Revert "Disable lab-extras repo and iozone installs"

- roles/testnode/tasks/yum/packages.yml
- roles/testnode/vars/redhat_7.yml
- roles/testnode/vars/yum_systems.yml
Rhel packages that needs to be added or removed to satisfy dependency and work across various ceph releases without conflict, Still in testing.
> rhel package changes required for ceph

- roles/common/defaults/main.yml
- roles/common/tasks/apt_systems.yml
- roles/common/tasks/main.yml
- roles/common/tasks/yum_systems.yml
Yes, this will cause the tz to be changed on lots of our systems. I'm unsure if this could actually break things, so feedback is appreciated.
> common: Set timezone (defaults to UTC)

- roles/testnode/README.rst
- roles/testnode/defaults/main.yml
- roles/testnode/tasks/apt/repos.yml
- roles/testnode/tasks/yum/gpg_keys.yml
> Stop looking for keys on git.ceph.com

- roles/testnode/README.rst
- roles/testnode/tasks/apt/repos.yml
- roles/testnode/tasks/yum/gpg_keys.yml
> Include /keys in path to key files, and document what's expected

- roles/cobbler/templates/snippets/cephlab_packages_rhel
- roles/common/tasks/yum_systems.yml
> Install yum on Fedora 22 and higher

- roles/ansible-managed/tasks/main.yml
- roles/cobbler/defaults/main.yml
- roles/cobbler/templates/kickstarts/cephlab_ubuntu.preseed
- roles/cobbler/templates/snippets/cephlab_user
- roles/paddles/tasks/setup_db.yml
- roles/paddles/tasks/setup_paddles.yml
- roles/pulpito/tasks/main.yml
- roles/sudo/defaults/main.yml
- roles/teuthology/tasks/setup_users.yml
This PR and the relevant secrets PRs would have to be merged at the same time, and probably have me around to make sure the changes get applied.
> Preparation for ansible 2.x

- roles/common/tasks/kerberos.yml
...rather than ansible_distribution
Fixes: #14751
> common/tasks/kerberos.yml: Test ansible_os_family for packaging type

- roles/testnode/vars/centos_7.yml
Fixes http://tracker.ceph.com/issues/14848
Signed-off-by: Yuri Weinstein <yweinste@redhat.com>
> Added "- ncurses-devel" for xfstests to run and pass

- ansible.cfg
Reverts ceph/ceph-cm-ansible#203
> Revert "ansible.cfg: do not set vault_password_file"

- callback_plugins/failure_log.py
This commit maintains backward compatibility
> Adapt failure_log plugin to work with ansible 2.0

- roles/cobbler/templates/triggers/install/post/cephlab_ansible.sh
http://tracker.ceph.com/issues/14725
> cobbler: enable stock OS provisioning

- cobbler.yml
http://tracker.ceph.com/issues/14982
> Prep for RHEL6.8

- roles/testnode/files/nagios/nrpe.te
- roles/testnode/tasks/main.yml
- roles/testnode/tasks/nrpe-selinux.yml
This addresses SELinux denials on CentOS and RHEL testnodes.
> testnodes: configure selinux for nagios monitoring

- roles/gateway/README.rst
> gateway: Add logrotate to to-do

- roles/gateway/templates/auth-openvpn
> gateway: modify auth-openvpn script to ignore comments and blank lines

- roles/testnode/vars/centos_7.yml
- roles/testnode/vars/debian_7.yml
- roles/testnode/vars/redhat_7.yml
- roles/testnode/vars/ubuntu.yml
Signed-off-by: Thierry Delamare <t.delamare@laposte.net>
Signed-off-by: Loic Dachary <loic@dachary.org>
> replace hardcoded x86_64 with {{ansible_architecture}}

- roles/testnode/tasks/yum_systems.yml
- roles/testnode/vars/apt_systems.yml
- roles/testnode/vars/yum_systems.yml
Ran in sjust@teuthology:/a/samuelj-2016-03-29_21:23:46-rados-wip-sam-testing-distro-basic-smithi
> Don't use sudo for rpm --rebuild-db and remove more packages for testnode

- cephlab.yml
- pcp.yml
- roles/pcp/README.rst
- roles/pcp/defaults/main.yml
- roles/pcp/files/1h1m.json
- roles/pcp/meta/main.yml
- roles/pcp/tasks/collector.yml
- roles/pcp/tasks/main.yml
- roles/pcp/tasks/manager.yml
- roles/pcp/tasks/prep.yml
- roles/pcp/tasks/web.yml
- roles/pcp/templates/target-discovery
- roles/pcp/templates/target-host
- roles/pcp/vars/apt_systems.yml
- roles/pcp/vars/dnf_systems.yml
- roles/pcp/vars/yum_systems.yml
This is still a work in progress.
Lots of information on PCP is available here:
http://pcp.io/docs/guide.html
> A role for PCP

- roles/testnode/templates/nagios/nrpe.cfg
> testnodes: Set sane warn/crit thresholds for nagios check_load

- roles/testnode/tasks/setup-ubuntu-non-aarch64.yml
- roles/testnode/vars/ubuntu.yml
- roles/testnode/vars/ubuntu_12.04.yml
- roles/testnode/vars/ubuntu_14.yml
- roles/testnode/vars/ubuntu_15.yml
Signed-off-by: Loic Dachary <loic@dachary.org>
> testnodes: add ubuntu 16.04 xenial support

- roles/pcp/README.rst
- roles/pcp/defaults/main.yml
- roles/pcp/tasks/main.yml
- roles/pcp/tasks/repo.yml
- roles/pcp/vars/apt_systems.yml
- roles/pcp/vars/yum_systems.yml
> pcp: Optionally use upstream package repos

- roles/pcp/files/index.js
- roles/pcp/tasks/web.yml
The main intent for this is to provide a link to view performance stats relevant to each teuthology job.
I'm open to feedback re: the name of the dashboard.
> pcp: A dynamic dashboard with host- and time-selection

- roles/testnode/tasks/apt/packages.yml
Signed-off-by: Samuel Just <sjust@redhat.com>
> testnode/tasks/apt/packages.yml: just force everything

- roles/testnode/vars/centos_6.yml
- roles/testnode/vars/centos_7.yml
Signed-off-by: wangsongbo <wangsongbo@unitedstack.com>
> testnode: replace hardcoded 'gitbuilder.ceph.com' with {{ gitbuilder_host }}

- roles/pcp/tasks/permissons.yml
http://tracker.ceph.com/issues/16119
Fixes: 16119
> pcp: Don't fail when setting permissions

- roles/testnode/tasks/resolvconf.yml
> Don't rely on LSB when testing for distro version

- roles/users/defaults/main.yml
- roles/users/tasks/create_users.yml
- roles/users/tasks/filter_users.yml
- roles/users/tasks/main.yml
- roles/users/tasks/revoke_users.yml
- roles/users/tasks/update_keys.yml
The speedup depends on changes like https://github.com/ceph/ceph-sepia-secrets/pull/135 - but this PR won't break the current behavior
> users: Greatly speed up ssh pubkey deployment

- roles/users/tasks/update_keys.yml
> Only clone the keys repo once per execution

- roles/testnode/tasks/main.yml
- roles/testnode/tasks/redhat/rhel_7.yml
- roles/testnode/tasks/setup-ubuntu.yml
Fixes: http://tracker.ceph.com/issues/15316
> testnodes: Configure cpan and install Amazon::S3 on all OSes

- roles/cobbler/tasks/pip.yml
> Add missing pip.yml

- roles/common/tasks/rhel-entitlements.yml
> common: Fix boolean expressions

- roles/users/tasks/update_keys.yml
http://tracker.ceph.com/issues/16615
Fixes: 16615
> Don't use a shallow copy of keys.git

- roles/cobbler/templates/triggers/install/post/cephlab_ansible.sh
> Use flock to avoid race conditions with git

- roles/users/tasks/update_keys.yml
> Add a retry when cloning the keys repo

- ansible_managed.yml
- pcp.yml
- testnodes.yml
- teuthology.yml
See http://docs.ansible.com/ansible/playbooks_strategies.html#strategies
This could potentially improve performance.
> Use strategy: free on some playbooks

- ansible.cfg
This may help with some of the problems we've been seeing.
Related to http://tracker.ceph.com/issues/16826
Inspired by
https://github.com/ansible/ansible/issues/13401#issuecomment-216768025
> Retry SSH connections five times

- roles/teuthology/tasks/setup_log_access.yml
- roles/teuthology/vars/apt_systems.yml
Ran into these two issues when running teuthology role against new teuthology VM.
> A couple fixes to teuthology role

- roles/common/README.rst
- roles/common/tasks/nagios.yml
- roles/common/vars/apt_systems.yml
- roles/common/vars/yum_systems.yml
check_load nagios plugin needs to be installed on RHEL and CentOS
> common: Install a few additional packages for NRPE

- cobbler.yml
- roles/cobbler_profile/defaults/main.yml
> Add RHEL7.3 support

- firmware.yml
- roles/firmware/README.rst
- roles/firmware/defaults/main.yml
- roles/firmware/tasks/areca/areca-update.yml
- roles/firmware/tasks/areca/main.yml
- roles/firmware/tasks/main.yml
- roles/firmware/tasks/mira/bios-update.yml
- roles/firmware/tasks/mira/bios.yml
- roles/firmware/tasks/mira/bmc-update.yml
- roles/firmware/tasks/mira/bmc.yml
- roles/firmware/tasks/smithi/bmc-update.yml
- roles/firmware/tasks/smithi/bmc.yml
- roles/firmware/tasks/smithi/nvme.yml
Merge with https://github.com/ceph/ceph-sepia-secrets/pull/184
> New role for updating firmware

- roles/nameserver/README.rst
- roles/nameserver/defaults/main.yml
- roles/nameserver/templates/named.conf.j2
Merge https://github.com/ceph/ceph-sepia-secrets/pull/186 first.
> nameserver: Add support for enabling/disabling recursion

- roles/cobbler/templates/kickstarts/cephlab_ubuntu.preseed
- roles/cobbler/templates/snippets/cephlab_packages_rhel
- roles/cobbler/templates/triggers/install/post/cephlab_ansible.sh
- roles/testnode/tasks/main.yml
- roles/testnode/tasks/zap_disks.yml
Tested on smithi, mira, VPS, and magna.
https://paste.fedoraproject.org/484007/79414931/
Fixes: http://tracker.ceph.com/issues/15951
> Zap all non-root disks on testnodes

- cobbler.yml
- roles/cobbler_profile/defaults/main.yml
> Add CentOS 7.3 to Cobbler

- roles/nameserver/README.rst
- roles/nameserver/tasks/main.yml
- roles/nameserver/templates/named.conf.j2
> nameserver: Add support for BIND slave nameservers

- roles/nameserver/tasks/main.yml
> nameserver: Fix permissions on /var/named/zones

- roles/nameserver/vars/packages.yml
> nameserver: Install redhat-lsb-core for `lsb_release`

- nsupdate_web.yml
- roles/nsupdate_web/README.rst
- roles/nsupdate_web/defaults/main.yml
- roles/nsupdate_web/tasks/main.yml
- roles/nsupdate_web/templates/nsupdate-web.service
- roles/nsupdate_web/templates/nsupdate_web_nginx
- roles/nsupdate_web/vars/ubuntu_16.yml
See https://github.com/zmc/nsupdate-web/
> Add role for nsupdate_web

- ansible.cfg
See https://github.com/ansible/ansible/pull/16560 and
https://github.com/ansible/ansible/issues/14219
> Reduce 'internal_poll_interval' to stem the CPU usage tide

- tools/vmlist.py
> tools: Replace mira091 w mira005 and add missing hv03

- public_facing.yml
- roles/public_facing/README.rst
- roles/public_facing/defaults/main.yml
- roles/public_facing/handlers/main.yml
- roles/public_facing/tasks/download.ceph.com.yml
- roles/public_facing/tasks/fail2ban.yml
- roles/public_facing/tasks/main.yml
- roles/public_facing/tasks/status.sepia.ceph.com.yml
- roles/public_facing/tasks/ufw.yml
- roles/public_facing/templates/download.ceph.com/logrotate.j2
- roles/public_facing/templates/download.ceph.com/make_timestamp.j2
- roles/public_facing/templates/f2b.filter.j2
- roles/public_facing/templates/f2b.jail.local.j2
- roles/public_facing/templates/f2b.service.j2
- roles/public_facing/templates/f2b_ufw.conf.j2
- roles/public_facing/templates/status.sepia.ceph.com/lab-pings.j2
- roles/public_facing/templates/status.sepia.ceph.com/nagios-eventhandler-cachet.config.j2
- roles/public_facing/templates/status.sepia.ceph.com/openvpn.j2
This role will probably be forever-growing but it's at a point, now, where fail2ban and UFW are at least managed on all hosts.
> public_facing role

- roles/common/tasks/kerberos.yml
> common: Fix a bug in PR #312

- roles/public_facing/tasks/www.ceph.com.yml
> public_facing: Add cronjobs for www.ceph.com

- roles/testnode/vars/ubuntu_16.yml
Fixes: http://tracker.ceph.com/issues/13522#note-51
> Update libgoogle-perftools4 on Xenial

- cobbler.yml
- roles/cobbler_profile/defaults/main.yml
> cobbler: Add RHEL 7.4

- roles/public_facing/tasks/download.ceph.com.yml
> public_facing: Changes to download.ceph.com crontab

- roles/teuthology/README.rst
> teuthology: minor README update

- roles/common/templates/nagios/90-nagios
> common: Grant nrpe user access to `sudo nvme`

- tools/cobbler-access.sh
> tools: Script to simplify Cobbler user creation

- cobbler.yml
- roles/cobbler_profile/defaults/main.yml
> cobbler: Add CentOS 7.4

- roles/public_facing/tasks/letsencrypt_nginx.yml
> public_facing: Finally get letsencrypt automated renewal  working

- roles/testnode/templates/apt/ceph.pref
> testnode: Update apt pinning URL

- roles/testnode/README.rst
- roles/testnode/tasks/drive_partitioning.yml
- roles/testnode/tasks/main.yml
We'll need to make sure https://github.com/ceph/ceph-sepia-secrets/pull/267 gets merged and updated on the teuthology host the same time this gets merged.
> Re-do how we partition drives

- roles/testnode/tasks/zap_disks.yml
> testnode: Update dependencies for zap tasks

- roles/testnode/tasks/main.yml
- roles/testnode/tasks/var_lib.yml
- roles/testnode/tasks/zap_disks.yml
Fixes: http://tracker.ceph.com/issues/20910
> testnode: Mount /var/lib/ceph to NVMe partition on smithi

- roles/testnode/tasks/zap_disks.yml
Fixes: http://tracker.ceph.com/issues/21989
Fixes: http://tracker.ceph.com/issues/21935 (hopefully)
> testnode: Be super aggressive with wiping LVM data

- roles/testnode/vars/ubuntu.yml
... on Ubuntu, for add-apt-repository
> testnode: Install software-properties-common

- roles/testnode/tasks/var_lib.yml
> Omit XFS options on older OSes

- tools/prep-fog-capture.yml
> tools: Delete ssh keys so FOG-imaged machines regenerate on firstboot

- tools/generate-fog-csv.yml
- tools/roles/generate-fog-csv/tasks/main.yml
- tools/roles/generate-fog-csv/templates/csv.j2
> tools: Add ansible role to generate FOG host csv file

- roles/cobbler_profile/defaults/main.yml
> cobbler_profile: Replace 16.04 with 16.04.3 iso

- roles/testnode/tasks/zap_disks.yml
> testnode: Stop zapping loop devices

- roles/testnode/tasks/zap_disks.yml
Saw this on smithi while testing new LVM changes
> testnode: Also stop zapping ram# devices

- roles/testnode/README.rst
- roles/testnode/tasks/configure_lvm.yml
- roles/testnode/tasks/lvm.yml
Fixes: http://tracker.ceph.com/issues/22328
> testnode: Add support to quickly create LVs

- tools/set-bmc-static.yml
> tools: Playbook for setting BMC settings

- roles/testnode/README.rst
- roles/testnode/tasks/main.yml
- roles/testnode/tasks/secondary_nic.yml
> testnode: Support for configuring a second NIC

- cobbler.yml
- roles/cobbler_profile/defaults/main.yml
> cobbler: Profile for RHEL7.5

- tools/update-nvme-firmware.yml
> tools: Playbook to update Intel NVMe firmware

- roles/testnode/README.rst
- roles/testnode/defaults/main.yml
- roles/testnode/tasks/check-for-nvme.yml
- roles/testnode/tasks/main.yml
> testnode: Check for and mark down systems with missing NVMe devices

- ntp-server.yml
- roles/ntp-server/README.rst
- roles/ntp-server/tasks/main.yml
- roles/ntp-server/templates/chrony.conf.j2
- roles/ntp-server/templates/ntp.conf.j2
> ntp-server: Create NTP server role

- roles/firmware/tasks/mira/bios-update.yml
> firmware: flashrom syntax changed for Xenial

- tools/prep-fog-capture.yml
> tools: Unsubscribe RHEL machines during FOG image capture

- roles/gateway/files/openvpn.logrotate
> gateway: Rotate every day.. not when size is 100MB

- roles/common/files/libexec/smart.sh
> common: Fixes to smart.sh to support multiple attributes

- roles/cobbler/templates/snippets/cephlab_rhel_rhsm
> cobbler: Fix typo in subscription manager snippet command

- roles/public_facing/templates/status.sepia.ceph.com/openvpn.j2
Script was creating too many false alerts
> public_facing: Updates to OpenVPN check for status portal

- long_running_cluster.yml
- roles/long_running_cluster/tasks/logrotate.yml
- roles/long_running_cluster/tasks/main.yml
- roles/long_running_cluster/tasks/nagios.yml
- roles/long_running_cluster/templates/ceph-common.logrotate
Additional tasks are needed (adding repos comes to mind).
> long_running_cluster role

- roles/teuthology/README.rst
- roles/teuthology/defaults/main.yml
- roles/teuthology/tasks/main.yml
- roles/teuthology/templates/update-crontab.sh
Fixes: https://tracker.ceph.com/issues/23441
> teuthology: Script to keep teuthology user's crontab up to date

- roles/common/tasks/main.yml
- roles/common/tasks/yum_systems.yml
@dmick - I know you spent a lot of time looking into NTP and hardware clocks.  Do you recall anything that might make this problematic?
> Always set hardware clock

- roles/common/tasks/rhel-entitlements.yml
Fixes: https://tracker.ceph.com/issues/23954
See also: https://bugzilla.redhat.com/show_bug.cgi?id=1510658
> common: Force register with RHSM

- roles/common/tasks/rhel-entitlements.yml
> common: Retry rhsm command due to CDN or network flakiness

- roles/testnode/vars/centos_6.yml
- roles/testnode/vars/centos_7.yml
- roles/testnode/vars/debian_7.yml
- roles/testnode/vars/debian_8.yml
- roles/testnode/vars/redhat_6.yml
- roles/testnode/vars/redhat_7.yml
- roles/testnode/vars/ubuntu.yml
- roles/teuthology/vars/apt_systems.yml
see https://github.com/ceph/swift/pull/7 and
https://github.com/ceph/s3-tests/pull/104
Signed-off-by: Kefu Chai <kchai@redhat.com>
> testnodes: s/libevent-dev/libev-dev/

- roles/pulpito/defaults/main.yml
- roles/pulpito/tasks/main.yml
- roles/pulpito/tasks/setup_pulpito.yml
- roles/pulpito/tasks/zypper_systems.yml
- roles/pulpito/vars/zypper_systems.yml
Signed-off-by: Kyr Shatskyy<kyrylo.shatskyy@suse.com>
> Add zypper support for pulpito role

- roles/paddles/tasks/main.yml
- roles/paddles/tasks/setup_paddles.yml
- roles/paddles/tasks/setup_service.yml
- roles/paddles/tasks/setup_user.yml
- roles/paddles/tasks/zypper_systems.yml
- roles/paddles/vars/zypper_systems.yml
> Add zypper support for paddles role

- roles/teuthology/tasks/main.yml
- roles/teuthology/tasks/setup_log_access.yml
- roles/teuthology/tasks/setup_users.yml
- roles/teuthology/tasks/zypper_systems.yml
- roles/teuthology/templates/teuthology-worker.init
- roles/teuthology/templates/teuthology.yaml
- roles/teuthology/vars/apt_systems.yml
- roles/teuthology/vars/zypper_systems.yml
> Add zypper support for teuthology role

- cobbler.yml
- roles/cobbler/defaults/main.yml
- roles/cobbler/templates/kickstarts/cephlab_opensuse_leap.xml
- roles/cobbler/templates/snippets/cephlab_rc_local
- roles/cobbler/templates/snippets/cephlab_user
- roles/cobbler_profile/defaults/main.yml
- roles/common/tasks/zypper_systems.yml
- roles/testnode/tasks/ntp.yml
- roles/testnode/tasks/set_hostname.yml
- roles/testnode/tasks/zap_disks.yml
- roles/testnode/tasks/zypper/packages.yml
- roles/testnode/templates/chrony.conf
- roles/testnode/templates/ssh/sshd_config_opensuse_leap_NA
- roles/testnode/vars/opensuse_leap_15.0.yml
- roles/testnode/vars/zypper_systems.yml
- tools/prep-fog-capture.yml
Fixes: https://tracker.ceph.com/issues/35927
> Add support for OpenSUSE Leap 15.0

- roles/cobbler/templates/kickstarts/cephlab_rhel_sdi.ks
- roles/cobbler/templates/kickstarts/cephlab_ubuntu_sdi.preseed
This will get used when the Octo FOG Images job in Jenkins runs
> cobbler: Support installing to /dev/sdi for callypso machines

- cobbler.yml
- roles/cobbler_profile/defaults/main.yml
> Add CentOS 7.6

- roles/common/tasks/yum_systems.yml
Fixes: http://tracker.ceph.com/issues/24197
> common: Reboot RHEL7 testnodes in case of timedatectl/systemd issue

- roles/common/vars/redhat_7.yml
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1674764
> common: Add HA repo for RHEL7

- roles/testnode/README.rst
- roles/testnode/defaults/main.yml
- roles/testnode/tasks/pip.yml
- roles/testnode/vars/apt_systems.yml
- roles/testnode/vars/yum_systems.yml
For use with https://github.com/ceph/ceph/pull/26262
> testnode: Install remoto on testnodes

- roles/teuthology/defaults/main.yml
- roles/teuthology/tasks/setup_users.yml
> teuthology: make sure teuthology logs directory exists

- roles/teuthology/defaults/main.yml
- roles/teuthology/tasks/setup_users.yml
> teuthology: add branch parameter for git checkout

- roles/paddles/defaults/main.yml
- roles/paddles/tasks/setup_paddles.yml
> paddles: add branch parameter for git checkout

- roles/pulpito/defaults/main.yml
- roles/pulpito/tasks/setup_pulpito.yml
> pulpito: add branch parameter for git checkout

- roles/testnode/vars/redhat_7.yml
This package is missing in cloud images
> testnode: Install lvm2

- roles/nameserver/tasks/config.yml
- roles/nameserver/tasks/main.yml
> nameserver: ensure named directories have right owner and permissions

- roles/teuthology/tasks/main.yml
- roles/teuthology/templates/teuthology-worker.init
> teuthology: use variable for user name

- roles/teuthology/templates/nginx.conf
- roles/teuthology/templates/teuthology.yaml
> teuthology: use 'archive_base' variable instead of hardcoded value

- roles/nsupdate_web/defaults/main.yml
- roles/nsupdate_web/templates/nsupdate-web.service
- roles/nsupdate_web/templates/nsupdate_web_nginx
> nsupdate_web: add nsupdate_web_port parameter

- roles/nsupdate_web/vars/opensuse_leap_15.yml
> nsupdate_web: add leap 15 vars

- roles/nsupdate_web/tasks/main.yml
> nsupdate_web: make sure nsupdate user group exists

- roles/common/templates/yum_repo.j2
- roles/dhcp-server/templates/dhcpd.conf.j2
- roles/dhcp-server/templates/dhcpd.subnet.conf.j2
- roles/testnode/templates/yum_repo.j2
> python3: s/iteritems/items/

- roles/common/vars/redhat_8.yml
> common: Use internal EL8 repos

- roles/teuthology/defaults/main.yml
- roles/teuthology/templates/teuthology.yaml
> teuthology: add defaults for ceph_git_base_url

- roles/cobbler_systems/tasks/populate_systems.yml
> cobbler_systems: Only populate systems that have necessary vars defined

- roles/cobbler_profile/defaults/main.yml
> cobbler_profile: Updating SHA for Ubuntu Xenial

- cobbler.yml
- roles/cobbler_profile/defaults/main.yml
Adding RHEL7.7-x86_64 to cobbler_profile
> Add RHEL7.7

- roles/dhcp-server/tasks/main.yml
> dhcp-server: Only restart dhcpd if something changed

- roles/cobbler/templates/triggers/install/post/cephlab_ansible.sh
> cobbler: Check for rhel8 or centos8 to set ansible_python_interpreter

- cobbler.yml
- roles/cobbler_profile/defaults/main.yml
- roles/common/defaults/main.yml
- roles/common/tasks/main.yml
- roles/common/tasks/nagios.yml
- roles/common/tasks/nrpe-selinux.yml
- roles/common/tasks/yum_systems.yml
- roles/common/vars/centos_8.yml
- roles/testnode/templates/ssh/sshd_config_centos_8
- roles/testnode/vars/centos_8.yml
Merge https://github.com/ceph/ceph-cm-ansible/pull/474 first
> CentOS8!!!

- roles/testnode/tasks/secondary_nic.yml
> testnode: Set MTU=9000 on 25Gb NICs too

- roles/cobbler/templates/triggers/install/post/cephlab_ansible.sh
> cobbler: EPEL8 has nagios packages so we needn't skip those tasks anymore

- cobbler.yml
- roles/cobbler_profile/defaults/main.yml
> cobbler: Add RHEL8.1 to lab

- roles/common/tasks/epel.yml
> common: Update yum metadata from upstream epel and exclude mirrors

- roles/testnode/vars/redhat_8.yml
> testnode: Install git on RHEL8

- roles/testnode/tasks/main.yml
- roles/testnode/tasks/pip.yml
- roles/testnode/templates/ssh/sshd_config_opensuse_leap_15
- roles/testnode/vars/opensuse_leap_15.1.yml
> testnodes: add opensuse 15.1 support

- cobbler.yml
- roles/cobbler_profile/defaults/main.yml
> cobbler: Add OpenSUSE Leap 15.1

- roles/testnode/vars/opensuse_leap_15.1.yml
> testnode: add rsyslog etc for openSUSE 15.1

- cobbler.yml
- roles/cobbler_profile/defaults/main.yml
> Add CentOS 7.7

- roles/teuthology/vars/zypper_opensuse_leap_15.1.yml
> teuthology: add python3 deps for leap 15.1

- roles/testnode/vars/redhat_8.yml
> testnode: Add lab-extras repo to RHEL8

- roles/testnode/vars/centos_8.yml
> testnode: lab-extras for centos_8 too

- roles/testnode/README.rst
- roles/testnode/defaults/main.yml
- roles/testnode/tasks/yum/repos.yml
- roles/testnode/vars/centos_8.yml
- roles/testnode/vars/redhat_8.yml
> testnode: Support adding copr repos

- roles/common/defaults/main.yml
- roles/common/templates/epel-mirrorlist
- roles/common/templates/epel-testing-mirrorlist
> common: Add missing 'Everything' subdir to EPEL8 URLs

- roles/testnode/vars/centos_7.yml
- roles/testnode/vars/redhat_7.6.yml
- roles/testnode/vars/redhat_7.8.yml
- roles/testnode/vars/redhat_7.yml
> testnode: Install python3 on CentOS/RHEL 7

- roles/testnode/vars/centos_8.yml
- roles/testnode/vars/redhat_8.yml
> el8: install gcc

- roles/testnode/vars/redhat_8.yml
> temporarily require python3-pytz

- roles/testnode/vars/centos_8.yml
- roles/testnode/vars/redhat_8.yml
> testnode: el8: libacl-devel

- roles/testnode/vars/centos_8.yml
- roles/testnode/vars/redhat_8.yml
> testnode: el8: dbench, autoconf

- roles/testnode/vars/centos_8.yml
- roles/testnode/vars/redhat_8.yml
> testnode: el8: install valgrind

- roles/testnode/vars/ubuntu_18.yml
Signed-off-by: Kefu Chai <tchaikov@gmail.com>
> testnode/var/ubuntu_18: python3-nose

- roles/testnode/vars/centos_8.yml
- roles/testnode/vars/redhat_8.yml
Signed-off-by: Jason Dillaman <dillaman@redhat.com>
> testnode: el8: qemu-kvm-core + qemu-kvm-block-rbd

- roles/testnode/vars/centos_8.yml
- roles/testnode/vars/redhat_8.yml
Signed-off-by: Jason Dillaman <dillaman@redhat.com>
> testnode: el8: nfs-utils

- roles/ansible-managed/tasks/main.yml
> ansible_managed: Remove unmanaged keys

- roles/testnode/tasks/yum/packages.yml
> testnode: Fix typo so task only runs on EL8

- cobbler.yml
- roles/cobbler_profile/defaults/main.yml
> Add CentOS 8.1

- roles/cobbler/templates/snippets/cephlab_rc_local
Fixes: https://tracker.ceph.com/issues/44158
> cobbler: Correct ifcfg syntax for OpenSUSE

- cobbler.yml
- roles/cobbler_profile/defaults/main.yml
> Adding Fedora 31 to sepia cobbler

- roles/testnode/vars/opensuse_leap_15.2.yml
Fixes: https://tracker.ceph.com/issues/44292
Signed-off-by: Nathan Cutler <ncutler@suse.com>
> testnodes: add vars for opensuse_leap_15.2

- roles/common/tasks/nagios.yml
- roles/common/vars/fedora_31.yml
> Adding Fedora 31 support to the common role

- cobbler.yml
- roles/cobbler_profile/defaults/main.yml
- roles/testnode/vars/opensuse_leap_15.2.yml
> Add OpenSUSE 15.2

- cobbler.yml
- roles/cobbler_profile/defaults/main.yml
> Adding CentOS-8.1.1911-aarch64 to cobbler

- tools/prep-fog-capture.yml
Hopefully fixes: https://github.com/ceph/ceph-cm-ansible/pull/544#issuecomment-599076564
> prep-fog-capture: Clean yum cache

- roles/testnode/tasks/zypper/packages.yml
Fixes: https://tracker.ceph.com/issues/44501
> testnode: Set ansible_python_interpreter for OpenSUSE

- cobbler.yml
- roles/cobbler_profile/defaults/main.yml
> cobbler: Add RHEL8.2

- tools/prep-fog-capture.yml
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1814337
> prep-fog-capture: Disable dnf-makecache service on EL8

- roles/testnode/README.rst
- roles/testnode/tasks/yum/repos.yml
> testnode: Add support for additional yum repos defined in secrets

- roles/common/tasks/nagios.yml
Not sure if this was a change in new NRPE or Ubuntu but let's just set both and cover our bases
> common: Also define new NRPE_OPTS var

- roles/common/tasks/rhel-entitlements.yml
> common: Define release with subscription-manager

- roles/common/tasks/rhel-entitlements.yml
Why is this even necessary, Satellite?!
> common: Retry setting rhsm release

- roles/common/tasks/rhel-entitlements.yml
> common: Retries does nothing without until

- roles/common/tasks/rhel-entitlements.yml
Getting really REALLY sick of workarounds for ~*~Satellite~*~
> common: Retry setting release for 2 minutes

- roles/common/tasks/rhel-entitlements.yml
Satellite, you make me very sad.
> common: Retry registering for 2 minutes

- roles/dhcp-server/README.rst
- roles/dhcp-server/tasks/main.yml
> dhcp-server: Skip configuring firewalld if not installed

- roles/dhcp-server/tasks/main.yml
> dhcp-server: firewalld_cmd.msg has to be defined to be evaluated

- roles/testnode/README.rst
- roles/testnode/defaults/main.yml
- roles/testnode/tasks/yum/abrt.yml
- roles/testnode/tasks/yum_systems.yml
Rachana requested this.
Fixes: https://tracker.ceph.com/issues/45824
> testnode: Configure ABRT

- roles/testnode/vars/centos_8.yml
- roles/testnode/vars/redhat_8.yml
> testnode: Stop using Ken's copr repo

- cobbler.yml
- roles/cobbler_profile/defaults/main.yml
- roles/cobbler_profile/tasks/import_distro_iso.yml
> Adding Centos-7.8-aarch64 to cobbler

- cobbler.yml
- roles/cobbler_profile/defaults/main.yml
> Adding RHEL7.9 and Centos8.2 to Sepia & Octo

- cobbler.yml
- roles/cobbler_profile/defaults/main.yml
> Add RHEL8.3

- tools/prep-fog-capture.yml
> Modify playbook to function with chrony

- roles/common/README.rst
- roles/common/tasks/container_mirror.yml
- roles/common/tasks/main.yml
- roles/common/vars/centos_7.yml
- roles/common/vars/centos_8.yml
- roles/common/vars/redhat_7.yml
- roles/common/vars/redhat_8.yml
> common: Support for container mirror CA certs

- roles/testnode/tasks/cachefilesd.yaml
> testnode: Restart cachefilesd in new kernel

- roles/container-host/tasks/container_mirror.yml
> container-host: Fix service restart syntax

- roles/paddles/tasks/setup_paddles.yml
- roles/paddles/vars/apt_systems.yml
- roles/paddles/vars/zypper_systems.yml
- roles/pulpito/tasks/setup_pulpito.yml
- roles/pulpito/vars/apt_systems.yml
- roles/pulpito/vars/yum_systems.yml
- roles/pulpito/vars/zypper_systems.yml
- roles/teuthology/tasks/main.yml
- roles/teuthology/vars/apt_systems.yml
- roles/teuthology/vars/zypper_opensuse_leap_15.2.yml
> teuthology: py3 for pulpito and paddles

- roles/rook-recovery/tasks/main.yml
- roles/rook-recovery/tasks/master-update.yml
- roles/rook-recovery/vars/main.yml
And also doing changes to the rook-recovery role
> Creating a new tag for updating the master os - master-update

- roles/common/tasks/apt_systems.yml
Fixes: https://tracker.ceph.com/issues/49152
> common: Disable sleeping on Ubuntu 20.04 and later

- roles/testnode/vars/redhat_8.yml
Fixes: https://tracker.ceph.com/issues/48767
> Adding redhat-lsb, firewalld and wget to rhel8 testnodes

- roles/paddles/vars/apt_systems.yml
> paddles: Install lz4 for backups

- cobbler.yml
- roles/cobbler_profile/defaults/main.yml
> Add CentOS 7.9

- roles/testnode/tasks/yum/repos.yml
Fixes: https://tracker.ceph.com/issues/49771
> Adding the releasever variable to rhel7.9 testnodes

- cobbler.yml
- roles/cobbler_profile/defaults/main.yml
> Add CentOS 8.3

- roles/common/tasks/rhel-entitlements.yml
- roles/testnode/tasks/yum/repos.yml
> common: Set releasever on testnodes sooner

- cobbler.yml
- roles/cobbler/templates/kickstarts/cephlab_rhel.ks
- roles/cobbler/templates/kickstarts/cephlab_rhel_sdi.ks
- roles/cobbler/templates/kickstarts/cephlab_rhel_sdm.ks
- roles/cobbler/templates/snippets/cephlab_packages_rhel
- roles/cobbler/templates/snippets/cephlab_rc_local
- roles/cobbler/templates/triggers/install/post/cephlab_ansible.sh
- roles/cobbler_profile/defaults/main.yml
- roles/common/tasks/main.yml
- roles/common/tasks/yum_systems.yml
- roles/common/vars/centos_9.yml
- roles/container-host/vars/centos_9.yml
- roles/testnode/templates/ssh/sshd_config_centos_9
- roles/testnode/vars/centos_9.yml
> Add CentOS 9 Stream

- roles/container-host/tasks/main.yml
- roles/testnode/vars/redhat_7.yml
- roles/testnode/vars/redhat_8.yml
Downstream QE requested we stop installing podman-docker in their FOG images.
> Allow defining an alternate container_packages var

- roles/cobbler/templates/triggers/install/post/cephlab_ansible.sh
> cobbler: Run all available playbooks during postinstall

- tools/set-bmc-static.yml
But the ipmi group makes more sense
> We can use this for any system

- cobbler.yml
- roles/cobbler_profile/defaults/main.yml
> Add CentOS 8.4

- roles/cobbler_profile/tasks/import_distro.yml
> cobbler: Fix ansible conditional

- roles/container-host/tasks/container_mirror.yml
> container-host: Ensure git is installed

- roles/public_facing/README.rst
- roles/public_facing/tasks/ufw.yml
> public_facing: Support defining a src port for UFW rules

- roles/testnode/tasks/yum/repos.yml
- roles/testnode/tasks/yum/stream.yml
- roles/testnode/tasks/yum_systems.yml
- roles/testnode/vars/centos_8_stream.yml
https://tracker.ceph.com/issues/51638
> Add PowerTools repo to CentOS 8 Stream

- roles/container-host/tasks/container_mirror.yml
> Revert "Merge pull request #635 from ceph/wip-python-pip"

- roles/rook/tasks/rook-os-update.yml
> Fixed indentation on rook-os-update.yml

- tools/downstream-jenkins-sync-jobs.yml
> Adding jenkins ocp4 jobs restore playbook

- cobbler.yml
- roles/cobbler_profile/defaults/main.yml
> Adding rhel8.5 to sepia cobbler

- roles/dhcp-server/README.rst
- roles/dhcp-server/tasks/main.yml
> dhcp-server: Add a packages tag so I can skip the task

- roles/common/tasks/yum_systems.yml
- roles/common/templates/epel-mirrorlist
- roles/common/templates/epel-testing-mirrorlist
> common: Enable epel9

- roles/common/templates/epel-mirrorlist
- roles/common/templates/epel-testing-mirrorlist
> common: Fix epel repo template

- roles/nameserver/tasks/main.yml
- roles/nameserver/tasks/records.yml
> nameserver: Check for and print IP collisions

- callback_plugins/failure_log.py
Before, we looked recursively for a certain Ansible type in the values
of the dict; this broke when another type was added in Ansible, but was
made worse by the type being used in _keys_, not just values.
This is a better method.
> failure_log: Use a default YAML representer

- roles/cobbler_profile/defaults/main.yml
> cobbler_profile: Update Ubuntu 20.04 image URL

- roles/cobbler/templates/triggers/install/post/cephlab_ansible.sh
- roles/cobbler_profile/tasks/import_distro.yml
- tools/convert-to-centos-stream.yml
The previous method no longer works
> Fix non-stream to stream conversion

- roles/testnode/vars/centos_8.yml
- roles/testnode/vars/centos_8_stream.yml
> testnode: Remove duplicated common_yum_repos

- roles/nsupdate_web/defaults/main.yml
- roles/paddles/defaults/main.yml
- roles/public_facing/tasks/download.ceph.com.yml
- roles/pulpito/defaults/main.yml
- roles/rook/README.rst
- roles/rook/tasks/rook-jenkins-update.yml
- roles/rook/tasks/rook-os-update.yml
- roles/rook/tasks/rook-recovery.yml
- roles/rook/vars/main.yml
- roles/teuthology/README.rst
- roles/teuthology/defaults/main.yml
- roles/teuthology/tasks/setup_users.yml
- roles/teuthology/templates/teuthology-worker.init
- roles/users/defaults/main.yml
Issues not addressed here:
- FOG still uses master
- lots of gitbuilder URLs in yaml files and docs referencing master
- named uses 'master zones'
> Inclusive language update

- cobbler.yml
- roles/cobbler_profile/defaults/main.yml
> Adding rhel9 to sepia cobbler

- cobbler.yml
- roles/cobbler_profile/defaults/main.yml
> cobbler: RHEL8.6

- roles/testnode/tasks/zap_disks.yml
> testnode: Add missing parenthesis to conditional

- tools/set-next-server-local.sh
- tools/switch-secrets.sh
> tools: Add a couple workstation scripts

- roles/common/tasks/rhel-entitlements.yml
Seriously... https://access.redhat.com/solutions/6438061
> common: Install Satellite RPM via rpm command

- container-host.yml
> container-host: s/slaves/builders

- tools/incerta-nic.yml
> tools: Playbook to configure incerta back NIC

- roles/testnode/tasks/apt/repos.yml
- roles/testnode/templates/ssh/sshd_config_ubuntu_22
- roles/testnode/vars/ubuntu_22.yml
> testnode: Ubuntu Jammy vars

- roles/cobbler/defaults/main.yml
- roles/cobbler/templates/kickstarts/cephlab_rhel_sdc.ks
> cobbler: Install on sdc for cali systems

- roles/cobbler/defaults/main.yml
- roles/cobbler/templates/kickstarts/cephlab_rhel.ks
- roles/cobbler/templates/kickstarts/cephlab_rhel_sdc.ks
- roles/cobbler/templates/kickstarts/cephlab_rhel_sdi.ks
- roles/cobbler/templates/kickstarts/cephlab_rhel_sdm.ks
- roles/cobbler/templates/snippets/cephlab_centos9_repos
- roles/cobbler/templates/triggers/install/post/cephlab_ansible.sh
> cobbler: Put CentOS9 Stream repos in place during kickstart

- roles/common/tasks/main.yml
> common: NRPE works on CentOS 9 now

- tools/cobbler-access.sh
See https://cobbler.readthedocs.io/en/v3.2.2/user-guide/web-interface.html#managing-users-digest
> cobbler-access: Update script to support Cobbler v3

- roles/cobbler/templates/snippets/cephlab_packages_rhel
> cobbler: CentOS 9 packages on CentOS 9 only

- roles/testnode/tasks/zap_disks.yml
Signed-off-by: Sun Junnan <sunjunnan_yewu@cmss.chinamobile.com>
Signed-off-by: Yang Honggang <yanghonggang_yewu@cmss.chinamobile.com>
> testnode: fix umount condition match error

- roles/testnode/tasks/cpan.yml
Fixes: http://pulpito.front.sepia.ceph.com/yuriw-2023-01-01_20:02:51-krbd-pacific_16.2.11_RC4-testing-default-smithi/7130439/
> Installing cpanminus on apt systems

- roles/common/tasks/rhel-entitlements.yml
https://pulpito.ceph.com/yuriw-2023-01-11_12:36:44-rbd-pacific_16.2.11_RC6-distro-default-smithi/7133168/
> Removed no_log to see the spacific errors

- roles/common/tasks/rhel-entitlements.yml
In continue to PR https://github.com/ceph/ceph-cm-ansible/pull/717
> Forgot to add use_satellite = true in two places

- roles/signalfx_splunk_agent_configuration/README.rst
- roles/signalfx_splunk_agent_configuration/defaults/main.yml
- roles/signalfx_splunk_agent_configuration/handlers/main.yml
- roles/signalfx_splunk_agent_configuration/tasks/http.yml
- roles/signalfx_splunk_agent_configuration/tasks/linux_installation.yml
- roles/signalfx_splunk_agent_configuration/tasks/main.yml
- roles/signalfx_splunk_agent_configuration/tasks/service_owner.yml
- roles/signalfx_splunk_agent_configuration/tasks/signalfx_main.yml
- roles/signalfx_splunk_agent_configuration/tasks/systemd.yml
- roles/signalfx_splunk_agent_configuration/tasks/ubuntu_installation.yml
- roles/signalfx_splunk_agent_configuration/tasks/yum_installation.yml
- roles/signalfx_splunk_agent_configuration/templates/http.yaml.j2
- roles/signalfx_splunk_agent_configuration/templates/systemd.yaml.j2
- roles/signalfx_splunk_agent_configuration/vars/main.yml
- signalfx.yml
Hi @akraitman,
Please do review this PR for me.
> Signalfx agent node configuration

- roles/paddles/tasks/main.yml
- roles/paddles/tasks/setup_postgres_exporter.yml
> paddles: Deploy postgres-exporter

- roles/testnode/vars/centos_8_stream.yml
Fixes: https://tracker.ceph.com/issues/62227
> centos_8_stream: install dbench package from epel

- cobbler.yml
Fixes: https://tracker.ceph.com/issues/61779
> Adding VMware ESXi-7.0 to cobbler

- cobbler.yml
- roles/cobbler_profile/defaults/main.yml
Fixes: https://tracker.ceph.com/issues/64148
> Adding rhel 9.3 to cobbler

- roles/grafana_agent/tasks/main.yml
Fixes: https://ibm.monday.com/boards/5591222586/pulses/8269716052
> Adding a validation to ensure /etc/apt/keyrings path exists

- roles/common/tasks/apt_systems.yml
- roles/testnode/tasks/pip.yml
- roles/testnode/templates/ssh/sshd_config_ubuntu_24
- roles/testnode/vars/ubuntu_24.yml
> Ubuntu Noble vars

- tools/checkcerts.py
also, remove Andrew Schoen and add David Galloway to email
> checkcerts.py: add telemetry.ceph.com to hosts to check
