roles/testnode/templates/resolvconf/base_octo

Remove apt-mirror.front from octo resolv.conf base config.

---

roles/common/tasks/rhel-entitlements.yml

The command module is skipped when --check is used which causes the
registered var subscription to not exist the next task fails.

Fixed bug where entitlement setup would fail with --check.

---

roles/common/defaults/main.yml
roles/testnode/defaults/main.yml

Commit 3d1ecaac01f9ed7a589741700fdb7fc22056218c moved the Red Hat subscription bits into the "common" role, but I neglected to move the default variables to "common" as well. Move them here.

move default rhsm vars to "common" role

---

roles/puddle/tasks/configure.yml
roles/puddle/templates/ceph-1.2-rhel-6-async.conf
roles/puddle/templates/ceph-1.2-rhel-7-async.conf

CEPH-ASYNC advisories have a slightly different config than the config we used for the 1.2.3 release. Here are the changes I made from the 1.2.3 configs:
1. "errata_release" is "CEPH-ASYNC"
2. Packages are not always signed (remove the keys settings)
3. We need to add more repos for repoclosure to succeed (namely, the
production read-only pulp repos)

puddle: add 1.2 configs for ceph-async

---

roles/testnode/tasks/user.yml

This fixes a bug when creating a CPAN config directory that belongs to the
group teuthology_user.  If this group wasn't created already that play
fails.

Add a teuthology_user group and assign it to the teuthology_user.

---

roles/cobbler/defaults/main.yml
roles/cobbler/tasks/upload_templates.yml
roles/cobbler/templates/kickstarts/cephlab_rhel.ks
roles/cobbler/templates/scripts/cephlab_preseed_late
roles/cobbler/templates/snippets/cephlab_rc_local
roles/cobbler/templates/triggers/install/post/cephlab_ansible.sh

For now it only uses ``--tags user,pubkeys``, because I'm not sure if running the whole thing is safe. It might be distro dependant and is definitely something we'd want to test carefully. This should be safe though.

Cobbler: automatically run ansible after install of new-style profiles

---

roles/puddle/tasks/configure.yml
roles/puddle/templates/ceph-1.3-rhel-7.conf
roles/puddle/templates/ceph-puddle

The first commit in this PR adds the new CEPH-TOOLS repository to Puddle for the Red Hat Ceph Storage 1.3 product.
The second commit in this PR adds a new `ceph-puddle` wrapper script to make it easier to run Puddle with Kerberos credentials.

puddle: add CEPH-TOOLS repo and `ceph-puddle` utility

---

cobbler.yml
roles/common/meta/main.yml
roles/users/defaults/main.yml
roles/users/tasks/create_users.yml
roles/users/tasks/main.yml
testnodes.yml
users.yml

This new role will be used to create users and setup authorized_keys for
lists of users defined in group inventory files.

Adds a users role and adds that role to cobbler.yml and testnodes.yml

---

roles/testnode/vars/redhat_7.yml

python-virtualenv was actually missed in the port, oops.  python-devel was new though.  At some point we should talk again about how we push this kind of stuff out to the task that needs it.  For now, I don't want to hold things up as we figure out the best way to do that.
re: http://tracker.ceph.com/issues/11637

Install python-devel and python-virtualenv on rhel 7.x

---

roles/puddle/tasks/nginx.yml

Follow the convention of putting each parameter on multiple lines, instead of cramming everything into one line.
This is a style change only; no functional change.

puddle: move nginx params on to multiple lines

---

roles/common/defaults/main.yml

Some of our labs should not be using epel.  This allows us to use
the enable_epel var to opt-out out of that per-lab by using the -secrets
repos.

Adds the ability to opt-out of enabling epel in the common role.

---

roles/testnode/tasks/main.yml

This is something chef does; ``teuthology.task.internal.vm_setup()`` expects it.

Testnode: touch /ceph-qa-ready

---

downstream_setup.yml
roles/downstream-setup/defaults/main.yml
roles/downstream-setup/tasks/main.yml
roles/downstream-setup/tasks/remove_yum_repos.yml
roles/downstream-setup/tasks/yum_repos.yml

This playbook will be used to setup testnodes for downstream
testing by downloading arbitrary yum repos. The repos to install should
be passed in with the --extra-vars option to ansible-playbook.
The yum_repos var must be a list of hashes defining the url to download
the repo from and the name to save it as in /etc/yum.repos.d
For example:
--extra-vars '{"yum_repos":[{"url": "<url>", "name": "name"}]}'
Or, removing repos from /etc/yum.repos.d::
-- extra-vars "remove_yum_repos=['name']"

Adds a new downstream_setup.yml playbook.

---

roles/cobbler_profile/tasks/download_iso.yml
roles/cobbler_profile/tasks/import_distro.yml

Otherwise we bail when trying to clear the mount point

Set iso_name and iso_path when not downloading

---

roles/ansible-managed/tasks/main.yml
roles/testnode/tasks/user.yml
roles/users/tasks/main.yml

They were ending up with sh, which is horrible

Set all created users' shells to /bin/bash

---

roles/downstream-setup/defaults/main.yml
roles/downstream-setup/tasks/main.yml

This lets us pass a teardown==True var to downstream-setup with the
yum_repos var defined and it will instead remove the repos defined in
yum_repos instead of downloading them.

downstream-setup: make yum_repos clean up after itself on teardown

---

roles/cobbler/defaults/main.yml
roles/cobbler/templates/scripts/cephlab_preseed_late
roles/cobbler/templates/snippets/cephlab_ubuntu_network

This is used to set the network connectivity for ubuntu nodes after
imaging using DHCP.
This is also creating a ``resolvconf`` var that I'm using in the snippet to set resolv.conf and resolv.conf.d/base during imaging.  I need to do that so DHCP will work and give us our IP after first boot.  Eventually we should have the testnodes role use this var as well and delete the hardcoded templates it uses.

cobbler: adds cephlab_ubuntu_network snippet

---

roles/testnode/tasks/yum_systems.yml

This doesn't reboot them to initiate autorelabel, but we can do that in the future if we need to.

Enable SELinux on yum systems

---

roles/downstream-setup/defaults/main.yml
roles/downstream-setup/tasks/main.yml

We want this change because using 'teardown' within teuthology was
confusing because we already have a method called 'teardown' on
class-based tasks.

downstream-setup: use 'cleanup' instead of 'teardown'

---

roles/downstream-setup/defaults/main.yml
roles/downstream-setup/tasks/disable_yum_repos.yml
roles/downstream-setup/tasks/enable_yum_repos.yml
roles/downstream-setup/tasks/main.yml

This works similar to downloading yum_repos. You can specific a repo
file to disable using 'disable_yum_repos' and enable them by using
'enable_yum_repos'. If you use 'disable_yum_repos' with 'cleanup' it
will enable the repos listed in 'disable_yum_repos' - this feature is
used with teuthology and the Ansible task.

downstream-setup: add tasks to disable and enable yum repos.

---

roles/cobbler/templates/scripts/cephlab_preseed_late
roles/testnode/handlers/main.yml
roles/testnode/tasks/apt_systems.yml
roles/testnode/tasks/nfs.yml
roles/testnode/templates/ssh/sshd_config_ubuntu_15
roles/testnode/vars/ubuntu.yml
roles/testnode/vars/ubuntu_15.yml

There are a few things here I feel need discussion before merge. 
1) We're not going to be maintain a package mirror for vivid and instead will use the distro provided mirror. This was discussed in irc, but more people can weigh in here if they care.
2) There are some packages that we install on other version of ubuntu that aren't available in vivid.  We're already removed mencoder, do we need to find alternate versions for the others commented out in vars/ubuntu_15.yml?
3) Vivid fails to 'enable' nfs-server, but can start it fine.  My first pass at debugging that didn't come up with anything as to why ansible can't 'enable' nfs-server. I'm unsure if this will be an issue or not.
I also have not tested this change against trusty to make sure I didn't break anything so I want to do that …

Support for ubuntu vivid

---

roles/cobbler/templates/snippets/cephlab_user

Apparently most other distros default anything in /etc/sudoers.d to
0440 except precise. Precise, by default, sets the mode of
/etc/sudoers.d/cephlab_sudo to 0664 which completely breaks sudo usage.
This makes cobbler explicitly set the mode to 0440.

cobbler: set the mode to 0440 on /etc/sudoers.d/cephlab_sudo

---

roles/testnode/defaults/main.yml
roles/testnode/handlers/main.yml
roles/testnode/vars/ubuntu_12.04.yml

rpcbind does not provide a way to be managed with upstart on precise.
This creates a var we can use to toggle this task on and off per distro
as the other distros we support are ok with starting and enabling rpcbind.

testnode: do not start rpcbind on precise

---

roles/downstream-setup/tasks/disable_yum_repos.yml
roles/downstream-setup/tasks/enable_yum_repos.yml

The lineinfile module fails if dest doesn't exist. We want this to fail
silently instead. The ansible output still does a good job of letting
you know a task failed without failing the entire playbook.
Sample output:
```
TASK: [downstream-setup | Disable yum repos.] *********************************
failed: [XXX.com] => (item=notthere) => {"failed": true, "item": "notthere", "rc": 257}
msg: Destination /etc/yum.repos.d/notthere.repo does not exist !
...ignoring
ok: [XXX.com] => (item=epel) => {"backup": "", "changed": false, "item": "epel", "msg": ""}
```

downstream-setup: ignore errors when disabling or enabling repos

---

roles/testnode/tasks/apt_systems.yml

I needed to cast ansible_distribution_major_version to an int for the
comparsion to work.

testnode: fixes a bug keeping apt repos from being added

---

roles/users/README.rst

Documentation for the users role.  I think we should start putting README files in each of the roles like this. Maybe eventually we can create a sphinx project that will collect all those and build docs that we could host somewhere.
Grammar nazi's welcome :)

users: add documentation for the users role

---

README.rst

We store everything related to our inventory in a repo separate from
this one. This commit explains that a bit better and the reasoning
behind it.

readme updates explaining the use of a separate secrets repo

---

roles/users/README.rst
roles/users/defaults/main.yml
roles/users/tasks/main.yml

If 'users' is provided it will filter 'managed_users'
and 'managed_admin_users' by the usernames provided in 'users'.
'users' must be a list of usernames as strings.

users: add a 'users' var to act as a filter

---

roles/testnode/tasks/user.yml

This is to work around cases where the user exists, with a different
uid, and we are currently logged in as that user:
msg: usermod: user ubuntu is currently logged in

Don't modify the teuthology_user if it is in use

---

roles/testnode/handlers/main.yml
roles/testnode/tasks/setup-ubuntu.yml
roles/testnode/templates/resolvconf/base
roles/testnode/templates/resolvconf/base_octo
roles/testnode/templates/resolvconf/base_typica

There is no need to modify resolv.conf for ubuntu anymore.  When using
cobbler this is set by using the resolvconf var in the cobbler role. For
vms, like ones created by openstack, this allows ubuntu nodes to use the
resolv.conf already provided.

testnode: do not modify resolv.conf on ubuntu

---

roles/ansible-managed/meta/main.yml
roles/ansible-managed/tasks/main.yml
roles/common/defaults/main.yml
roles/common/meta/main.yml
roles/sudo/README.rst
roles/sudo/defaults/main.yml
roles/testnode/defaults/main.yml
roles/testnode/tasks/redhat/set_hostname.yml
roles/testnode/tasks/setup-redhat.yml

I have not tested this yet, but wanted to put it up early for discussion.  I think this should allow the testnodes, ansible-managed and common roles to be used without a secrets repo.  I tried to address all the vars listed in @dachary's blog post here: http://dachary.org/?p=3752
See: http://tracker.ceph.com/issues/12256

roles used by teuthology should not require a secrets repo

---

roles/cobbler/tasks/redhat/rhel_6.yml
roles/cobbler/tasks/redhat/rhel_7.yml
roles/cobbler/tasks/setup-redhat.yml
roles/cobbler/tasks/yum_systems.yml

On EL7, poke holes for http and https. On EL6, just stop iptables.

Manage the firewall on RHEL/CentOS 6/7

---

roles/common/tasks/rhel-entitlements.yml

secrets_path comes from the secrets role and it is always defined.  It
will default to /etc/ansible/secrets if the env var ANSIBLE_SECRETS_PATH
is not defined. You can also define secrets_path by passing a variable
to the playbook being used.

common: |mandatory is not needed for secrets_path, it is always defined.

---

roles/testnode/tasks/user.yml

Warnings appeared each run:
[WARNING]: It is unnecessary to use '{{' in conditionals, leave variables in
loop expressions bare
Apparently 'when' clauses are already Jinja2 expressions, and so don't
need the normal variable quoting.

Fix warning in 'when' clause in 'Create the teuthology user.'

---

roles/cobbler/templates/kickstarts/cephlab_rhel.ks
roles/testnode/vars/centos_6.yml
roles/testnode/vars/centos_7.yml
roles/testnode/vars/fedora_20.yml
roles/testnode/vars/redhat_6.yml
roles/testnode/vars/redhat_7.yml

We need to make sure basic things like bzip2 are installed.

Install the Core and Base groups on rpm systems

---

roles/testnode/vars/centos_6.yml
roles/testnode/vars/centos_7.yml
roles/testnode/vars/fedora_20.yml
roles/testnode/vars/redhat_6.yml
roles/testnode/vars/redhat_7.yml

We don't want to install these anymore as they're causing issues with
the teuthology install task because of their dependency on librados.
See: http://tracker.ceph.com/issues/12371

testnode: remove scsci-target-utils and iscsi-initiator-utils

---

roles/users/tasks/main.yml

http://tracker.ceph.com/issues/12380
We're seeing transient issues connecting to githubusercontent.com. This
commit will cause ansible to retry three times with a five-second delay
between tries. Hopefully that's good enough.

Retry authorized_keys updates

---

cobbler.yml
roles/cobbler_profile/tasks/import_distro.yml

The other commit is needed because ``distros`` and ``extra_distros`` weren't merging properly.

Add RHEL 6.7

---

roles/testnode/templates/modules
roles/testnode/vars/ubuntu.yml

This is part of the work for http://tracker.ceph.com/issues/12424 which enables the ceph task in ceph/ceph-qa-suite to create and place osd/mon/mds in control groups.
For ubuntu, kernels for precise and up have `CONFIG_CGROUP_*` enabled, so the only thing that it's required is to install `cgroup-lite` which is a service that mounts the cgroups virtual FS. The `cgroup-bin` package will also be used from the ceph task to manipulate (create/modify/delete) control groups.
The `net_cls` subsystem is included as a module (named `cls_cgroup`) and is not enabled loaded by `cgroup-lite`, i.e. it has to be done explicitly. So we add it to `/etc/modules`

Adds cgroups packages and net_cls kernel module to ubuntu systems

---

cephlab.yml
roles/teuthology/meta/main.yml
teuthology.yml

So far, it only depends on the sudo and users roles. The playbook also
runs the common role.

Add teuthology role and playbook

---

roles/puddle/tasks/distill/configure.yml
roles/puddle/templates/ceph-1.2-rhel-6-async.conf
roles/puddle/templates/ceph-1.2-rhel-7-async.conf
roles/puddle/templates/ceph-1.3-rhel-7-async.conf

The first commit fixes our ceph-1.2-async configs to be more complete/user-friendly for QE, and the second commit cleans up the distill directory name that we finally ended up using.

Puddle updates

---

roles/testnode/tasks/ntp.yml

Tested with:
$ ansible-playbook -i ../ceph-octo-secrets/ansible/inventory/octo
--limit 'magna064*' --tag ntp-client testnodes.yml
Fixes: #12603

testnode/tasks/ntp: make sure ntpd is started

---

.gitignore
callback_plugins/failure_log.py

This callback plugin is called on every failure and prints out the
failure information as yaml so that it's easier to read in the
teuthology logs.
If the environment variable ANSIBLE_FAILURE_LOG is present then a log of
all failures in the playbook will be persisted to the file
path given in the ANSIBLE_FAILURE_LOG.

A callback plugin that logs failure message

---

roles/testnode/README.rst
roles/testnode/defaults/main.yml
roles/testnode/tasks/pip.yml
roles/testnode/tasks/yum/packages.yml
roles/testnode/vars/redhat_6.yml
roles/testnode/vars/redhat_7.yml

This separates packages we install from epel into their own list for rhel 6 and 7.
We do this so that we can install them with the epel repo explicitly enabled.

testnode: put epel packages in their own list for rhel 6 and 7

---

roles/testnode/tasks/vars.yml

We want to load distro specific variables before we load major version
specific variables. Loading of vars should happen in this order: package
manager, distro, major version, version.

testnode: fix var file loading order

---

roles/testnode/tasks/apt/repos.yml
roles/testnode/tasks/yum/gpg_keys.yml

Pulling them out of gitweb hits the server too hard.

use static versions of release.asc and autobuild.asc

---

roles/common/tasks/rhel-entitlements.yml

Bug was found by re-imaging RHEL7.1 system while customer portal was down, and thus, subscription-manager failed.
Ran testnodes playbook again after outage resolved and rhsm_repos were not disabled.
This resulted in yum-plugin-priorities installation failure due to missing item=rhel-7-server-optional-rpms repo
Remander of playbook failed at that point

Wip rhel entitlements

---

roles/testnode/vars/centos_6.yml
roles/testnode/vars/centos_7.yml

This allows the testnode role to provision centos nodes in a lab where epel is disabled.

testnode: add epel_packages for centos 6 and 7

---

roles/testnode/vars/apt_systems.yml
roles/testnode/vars/yum_systems.yml

It must be removed if present otherwise a firefly installation will
fail with:
Package python-ceph is obsoleted by python-rados,
but obsoleting package does not provide for requirements
or similar errors.
Signed-off-by: Loic Dachary <loic@dachary.org>

python-rados does not exist in firefly

---

roles/puddle/tasks/nginx.yml
roles/puddle/templates/nginx.conf

In Red Hat's (internal) DNS, dev-puddle is a CNAME to puddle. This PR sets up Nginx's configuration file to handle this new name and route the requests to a dedicated "dev-puddle" htdocs directory.
Update the nginx task to create multiple docroots, and add "dev-puddle" to be the second one.

puddle: add "dev-puddle" virtualhost

---

roles/puddle/defaults/main.yml
roles/puddle/tasks/configure.yml
roles/puddle/templates/ceph-1.3-rhel-7-async.conf
roles/puddle/templates/ceph-1.3.z-rhel-7.conf

Add a new Puddle configuration file for ceph-1.3.z.
Output to the "dev-puddle" location for now.
In RHCeph 1.3.1, we're introducing Foreman, which has a dependency on the SCL product. Add this to the Puddle configuration for the "Installer" repo.

puddle: add ceph-1.3.z config

---

roles/users/tasks/main.yml

When updating ssh keys for users we implemented a do until loop that
will account for transient issues when downloading the key from github.
The problem was that if the url fails then the var we were registering
was never created and the 'until' block errors out trying to check it.

users: fixes bug related to ssh key update retries

---

roles/puddle/tasks/distill/configure.yml

I recently switched rcm-metadata.git to use the git:// protocol instead of http://. When operating on a repository that uses a protocol other than HTTP, Ansible's git module unconditionally requires accept_hostkey to be set.
(See https://github.com/ansible/ansible-modules-core/issues/1931 for the upstream report.)

puddle: accept hostkey when cloning distill's rcm-metadata.git

---

roles/downstream-setup/tasks/cleanup.yml
roles/downstream-setup/tasks/disable_yum_repos.yml
roles/downstream-setup/tasks/enable_yum_repos.yml
roles/downstream-setup/tasks/main.yml
roles/downstream-setup/tasks/remove_yum_repos.yml
roles/downstream-setup/tasks/setup.yml
roles/downstream-setup/tasks/yum_repos.yml

This is a refactor that makes this role a bit easier to understand and
use. I've simplified main.yml to only include setup.yml and cleanup.yml.
This separation of cleanup and setup related tasks make it a bit easier
to understand.
Also fixes this bug: http://tracker.ceph.com/issues/12693

downstream-setup: separate cleanup and setup tasks into their own files

---

roles/common/defaults/main.yml
roles/testnode/vars/centos_6.yml
roles/testnode/vars/centos_7.yml
roles/testnode/vars/redhat_6.yml
roles/testnode/vars/redhat_7.yml

This enables mirrorlist functionality with the epel repo.
This should prevent package installation from breaking when yum runs into a connection timeout with the baseurl.

Enable mirrorlist for epel repo

---

roles/common/tasks/rhel-entitlements.yml

We were seeing "error while evaluating conditional: replace_repos" when
running against RHEL nodes which were missing entitlements. Even though
that won't be a particularly positive scenario, this was a bug that
should be fixed.

Common: If no entitlements, skip repo replacement

---

roles/common/defaults/main.yml
roles/common/tasks/epel.yml

We were getting timeouts when using epel mirrors and the default timeout value
is only 30 seconds which is not long enough for heavily used mirrors to
respond.
See: http://tracker.ceph.com/issues/12778

common: set timeout in /etc/yum.conf

---

roles/users/tasks/main.yml

We were still getting timeouts when requesting keys from github, so
we're gonna try to just simply increase the number of times it retries
to see if that helps things.
See: http://tracker.ceph.com/issues/12868

users: increase the retry count to 24 for fetching ssh keys from github

---

roles/testnode/tasks/apt/repos.yml

When updating the apt cache we have to make an http call out to
gitbuilder, if gitbuilder fails for whatever reason we should retry
before failing the playbook.
Also, this removes a 'changed_when: false' on 'Add local apt repos'.
We check it's 'changed' status to know if we need update the cache or
not. We only added that 'changed_when' to avoid seeing this task being
changed each time (because it will always change), but we actually need
that value set correctly because we use it in the 'when' clause of the
updating apt cache stanza.

testnode: retry when updating the apt cache to handle http errors

---

roles/common/tasks/kerberos.yml
roles/testnode/tasks/apt/repos.yml
roles/testnode/tasks/apt_systems.yml
roles/testnode/templates/apt/sources.list.jessie
roles/testnode/templates/ssh/sshd_config_debian_8
roles/testnode/vars/debian_8.yml

This adds support for debian 8. There were a few packages present in the packages list for debian 7 that are not present in debian 8.  I've just removed those for now and added a comment about them. I'm unsure how to determine if they're actually needed or not.
See: http://tracker.ceph.com/issues/12957

Add support for debian 8

---

roles/downstream-setup/tasks/cleanup.yml

Fixes: http://tracker.ceph.com/issues/12921
The issue here was that I was passing the hash ``yum_repos`` to ``remove_yum_repos.yml`` in ``cleanup.yml`` when it was expecting a list of repos as strings, causing the task to not find the correct yum repo to remove.

downstream-setup: yum_repos will now be removed during cleanup

---

roles/testnode/vars/centos_6.yml
roles/testnode/vars/debian_7.yml
roles/testnode/vars/fedora_20.yml
roles/testnode/vars/redhat_6.yml
roles/testnode/vars/ubuntu_12.04.yml

This repository contains packages that we don't have time to continue maintaining. In particular, the CentOS 6 QEMU packages were vulnerable to VENOM (CVE-2015-3456) and no users should rely on them. The other packages in "ceph-extras" will continue to incur security issues over time.
With the recent migration from "ceph.com" -> "download.ceph.com", we've chosen not to copy these "ceph-extras" files over to the new locations.

rm ceph-extras repository config

---

roles/testnode/vars/centos_6.yml
roles/testnode/vars/centos_7.yml
roles/testnode/vars/redhat_6.yml
roles/testnode/vars/redhat_7.yml

For Ceph upstream, we rely on fcgi from EPEL.
http://tracker.ceph.com/issues/13203 Refs: #13203

testnode: add fcgi to the list of EPEL packages

---

roles/testnode/vars/centos_6.yml
roles/testnode/vars/redhat_6.yml

Prior to this commit, every RHEL 6 and CentOS 6 node would automatically have the cuttlefish repository enabled.
This hardcoding seems wrong. Now that we've moved the RPMs off of ceph.com to download.ceph.com, it actually breaks nodes. So let's stop hard-coding this one altogether.
Reported-by: @wusui

testnode: rm cuttlefish repository

---

roles/common/defaults/main.yml
roles/common/tasks/epel.yml
roles/common/templates/epel-mirrorlist
roles/common/templates/epel-testing-mirrorlist

Related to:
http://tracker.ceph.com/issues/12739
http://tracker.ceph.com/issues/12778

Use local epel mirrorlist

---

roles/testnode/vars/centos_6.yml
roles/testnode/vars/centos_7.yml
roles/testnode/vars/redhat_6.yml
roles/testnode/vars/redhat_7.yml

This commit removes installation requirement of custom Ceph qemu packages that are no longer available for RHEL/CentOS6 and shouldn't be used on RHEL/CentOS7.
Repos containing these packages were removed in https://github.com/ceph/ceph-cm-ansible/commit/0d3dcfe3b3d85901016d6bb767ef17b5c791817e

Remove custom qemu packages

---

roles/puddle/templates/ceph-1.3-rhel-7-async.conf
roles/puddle/templates/ceph-1.3.z-rhel-7.conf
roles/puddle/templates/rh-common-rhel-6.conf
roles/puddle/templates/rh-common-rhel-7.conf

**output RHCEPH 1.3 to separate locations**
I periodically generate Puddles for both RHCS 1.3.0-async and 1.3.1. It's confusing when these Puddles exist in the same parent directory. Split them up into two directories so it is easier to understand what
each Puddle is.
**new RH-COMMON advisory undergoing testing**
Adjust the RHEL 6 and 7 RH-COMMON Puddle configs for a new async update that will be undergoing testing.

puddle: multiple updates

---

roles/ansible-managed/tasks/main.yml
roles/testnode/tasks/user.yml
roles/users/tasks/main.yml

If adding sudo, add as secondary group ('groups:').  This is more
standard, and allows for quick enumeration of "who's in sudo" by
examining /etc/group

Create users with same-named primary group

---

roles/paddles/tasks/main.yml

Currently this only stores the db_pass var. Also fix the name of the
play.

paddles: Always include secrets

---

roles/puddle/tasks/nginx.yml
roles/puddle/templates/nginx.conf

I'm adding HTTPS to our Puddle web server in order to support test Apt repos over HTTPS.
The packages will be hosted under http://puddle.fqdn/ubuntu/
The key and certificate files are managed outside of Ansible.

puddle: nginx configs for HTTPS

---

roles/testnode/vars/ubuntu_14.yml

Tests that need blkin are welcome to install it in a way that makes sense.
http://tracker.ceph.com/issues/13572
Signed-off-by: Loic Dachary <ldachary@redhat.com>

Temporarily disable blkin repo (part 2)

---

roles/testnode/tasks/yum_systems.yml

We were already doing this for apt systems; do it for yum systems as
well

testnodes: Add teuthology_user to 'disk' group

---

cobbler.yml
roles/cobbler_profile/defaults/main.yml

Changing `kernel_options:` in secrets repos

cobbler: renaming cobbler distro/profile to indicate autonuke/non-interactive

---

roles/testnode/tasks/set_hostname.yml

Instead of using convoluted logic to determine whether or not to set the
hostname, just do it. The hostname module is nice and idempotent.
This was inspired by http://tracker.ceph.com/issues/13679

testnodes: Set hostnames properly

---

roles/testnode/vars/centos_6.yml
roles/testnode/vars/centos_7.yml
roles/testnode/vars/fedora_20.yml
roles/testnode/vars/redhat_6.yml
roles/testnode/vars/redhat_7.yml

Several RBD test cases require QEMU to be present to verify integration.
Ubuntu package list already included QEMU packages.
Fixes: #13308
Signed-off-by: Jason Dillaman <dillaman@redhat.com>

testnode: install QEMU packages on Fedora, RHEL, and CentOS

---

roles/paddles/defaults/main.yml
roles/paddles/tasks/main.yml
roles/paddles/tasks/nginx.yml
roles/paddles/templates/nginx.conf
roles/paddles/templates/prod.py
roles/paddles/vars/apt_systems.yml

This is to avoid timeouts when gunicorn workers are busy.

Use nginx as a reverse proxy for paddles

---

roles/testnode/vars/redhat_6.yml
roles/testnode/vars/redhat_7.yml

Red Hat QE occasionally tests full in-place OS upgrades from RHEL 6 to
RHEL 7. When mod_fastcgi is pre-installed on a RHEL 6 node, and the node
is upgraded to RHEL 7, then Apache will refuse to start unless the QE
team member also upgrades the mod_fastcgi package explicitly. (see
https://bugzilla.redhat.com/1230679 for an example)
Since RGW's Civetweb is becoming mainstream, we don't really need to
focus on mod_fastcgi for Ceph any more, and having it pre-installed on
our RHEL nodes is more of a hindrance than a help.
I'm leaving the CentOS configs alone, for now, so we don't interfere
with any upstream testing with mod_fastcgi.

testnode: do not install fastcgi on RHEL

---

roles/cobbler_systems/tasks/populate_systems.yml

- This change will pull the 'kickstart_metadata' variables from the secrets repos and set ksmeta options for testnodes in Cobbler

cobbler: add ksmeta capabilities for cobbler_managed systems

---

roles/testnode/vars/centos_6.yml
roles/testnode/vars/centos_7.yml
roles/testnode/vars/debian_7.yml
roles/testnode/vars/debian_8.yml
roles/testnode/vars/fedora_20.yml
roles/testnode/vars/ubuntu.yml

This is temporary since we don't have those repos on the new gitbuilder
archive yet. Once we do, we should remove these mentions and replace
them with code in teuthology tasks which need fastcgi.

Disable fastcgi repos and package installs

---

roles/testnode/vars/centos_6.yml
roles/testnode/vars/centos_7.yml
roles/testnode/vars/redhat_6.yml
roles/testnode/vars/redhat_7.yml

Tests invoking iozone will still fail. But it's better than nothing, at
least until we get the apt-mirror data we're missing.

Disable lab-extras repo and iozone installs

---

roles/puddle/handlers/main.yml
roles/puddle/tasks/main.yml
roles/puddle/tasks/rsync.yml
roles/puddle/templates/rsyncd.conf

Run rsyncd with access to the "ubuntu" directory. This will permit Red Hat's rel-eng to view this repository layout.

puddle: add rsyncd

---

roles/puddle/templates/ceph-1.3-rhel-7-async.conf
roles/puddle/templates/ceph-1.3.z-rhel-7.conf

Now that RHCS 1.3.1 is released,
* Tweak the version numbers in Puddle. These numbers are cosmetic and control the names of the directories where Puddle puts its output. As explained in bfc268d7d11ce4757f44a8729830dff9ecb93df9, the purpose of the separate output directories is to allow the RH QE team to distinguish between "the next micro RHCS release" (in this case, 1.3.2), and any async updates we will ship for RHCS 1.3 in the meantime.
* Add ceph-1.3.z to the list of advisories to query in Red Hat's Errata Tool.

puddle: ceph-1.3.z adjustments

---

roles/testnode/tasks/nagios.yml

- Undo commit 2f28215cf79e596142986c8835040e5b1676849b
- Service should be restarted after nrpe.cfg is modified; not after the /etc/default/{{ nrpe_service_name }} file is modified
- /etc/default/{{ nrpe_service_name }} gets read anytime service is restarted

testnodes: fixing nrpe service configuration setup order

---

roles/users/tasks/main.yml

Filter the user lists after the other list-modifying
operations.  This way, the user-requested 'users' variable
filter has final say over which users are considered.

users: filter userlists against 'users' later

---

roles/testnode/vars/redhat_6.yml
roles/testnode/vars/redhat_7.yml

Sorry didn't realize without this rgw swift tests will fail on rhel, we will need this on rhel but should document for qe folks to uninstall it during upgrade tests.
Reverts ceph/ceph-cm-ansible#166

Revert "testnode: do not install fastcgi on RHEL"

---

roles/cobbler_profile/defaults/main.yml

This stops it prompting for a keymap on boot.

Add 'nokeymap' to inktank-rescue cobbler profile's kernel options

---

cobbler.yml
roles/cobbler_profile/defaults/main.yml

Also rename the old CentOS 7 profile to reflect that it is for 7.0

cobbler_profile: Add CentOS 7.1 and 7.2

---

roles/puddle/templates/ceph-1.3-rhel-7-async.conf
roles/puddle/templates/distill/ceph-distill

The first commit adds the SCL repository to the ceph-1.3-async configuration.
In RHCeph 1.3.1, we introduced Foreman, which has a dependency on the SCL
product. All async updates after this must use the SCL repo for repoclosure.
The second commit fixes an issue where our Distill wrapper script would fail
when Distill's "latest" symlink was not present.

puddle: fixes for ceph-1.3-async and distill

---

roles/vmhost/README.rst
roles/vmhost/files/interfaces
roles/vmhost/files/libvirt-net-front.xml
roles/vmhost/tasks/libvirt.yml
roles/vmhost/tasks/main.yml
roles/vmhost/tasks/networking.yml
roles/vmhost/tasks/packages.yml
roles/vmhost/vars/main.yml
vmhost.yml

This is mostly a transliteration, minus the unneeded/obsolete bits, of cookbook-vm-general.  It assumes that a host is installed and has had /srv/libvirtpool/vpmNNN set up to support the specific VMs that should live on this host.  For mira, that means the first vpm dir is on the root drive, and the 2-8th are on mounted filesystems.
Possible enhancement: make a map of vpm-to-vmhost in Ansible vars, and use it to drive the 'create /srv/libvirtpool' automatically.

Add vmhost role, supporting tasks, to provision VPS hosts

---

roles/vmhost/tasks/libvirt.yml

Fixing srv_libvirtpool check syntax

---

roles/cobbler/templates/snippets/cephlab_packages_rhel
roles/cobbler/templates/snippets/cephlab_rc_local

Cobbler would fail to create kickstart because non-Fedora distros would return 7.X, for example, as the integer resulting in non-Fedora kickstart creation to fail
Fixes: #14790

Fixes http://tracker.ceph.com/issues/14729

---

ansible.cfg

So that ansible-playbook can run from the root of the repository and not
pick up this value which is unlikely to be correct.
http://tracker.ceph.com/issues/14914 Fixes: #14914
Signed-off-by: Loic Dachary <loic@dachary.org>

ansible.cfg: do not set vault_password_file

---

roles/testnode/tasks/nagios.yml
roles/testnode/templates/nagios/nagios-nrpe-server

The variable name the systemd nrpe service looks for is <code>NRPE_SSL_OPT</code>
See <code>/usr/lib/systemd/system/nrpe.service</code>
The variable name nrpe on Ubuntu looks for is <code>DAEMON_OPTS</code>
Since the variable name *and* default configuration location differ between distros, we can get rid of the <code>roles/testnode/templates/nagios/nagios-nrpe-server</code> template and just set the single variable instructing NRPE to not use SSL.

testnodes: Disable ssl requirement for nrpe on rpm-based distros

---

roles/testnode/README.rst
roles/testnode/tasks/nagios.yml

Nothing had previously enabled the service to start at boot.
<pre>
[root@smithi014 ~]# systemctl list-unit-files nrpe.service
UNIT FILE    STATE   
nrpe.service disabled
</pre>

testnode: add check to make sure NRPE service is running

---

roles/cobbler/templates/kickstarts/cephlab_rhel.ks
roles/cobbler/templates/kickstarts/cephlab_ubuntu.preseed

testnodes get set to UTC as part of the testnodes playbook anyway.
This particular commit sets the right timezone from firstboot so no DHCP/NetworkManager/ntp confusion happens.
See http://tracker.ceph.com/issues/15126#note-2
And https://bugzilla.redhat.com/show_bug.cgi?id=1093803

cobbler: set testnodes timezone during kickstart

---

roles/testnode/tasks/nagios.yml
roles/testnode/templates/nagios/90-nagios
roles/testnode/templates/nagios/nrpe.cfg
roles/testnode/vars/apt_systems.yml
roles/testnode/vars/yum_systems.yml

NRPE on CentOS/RHEL ignore the nrpe_user variable in nrpe.cfg due to the
systemd init file.  See https://github.com/NagiosEnterprises/nrpe/issues/28
The 'nagios' user is created by default on *.deb
The 'nrpe' user is created by default on *.rpm
Further reading: https://www.mooash.me/2014/10/24/nagios-nrpe-ansible-role/

testnodes: Configure per-OS nrpe user and group name

---

gateway.yml
roles/gateway/README.rst
roles/gateway/defaults/main.yml
roles/gateway/meta/main.yml
roles/gateway/tasks/main.yml
roles/gateway/tasks/packages.yml
roles/gateway/tasks/users.yml
roles/gateway/templates/users.j2
roles/gateway/vars/packages.yml

This initial branch will allow us to maintain the OpenVPN users file by adding their username and hashed password to the `lab_users` list in the secrets repo.

New role to manage OpenVPN gateway

---

roles/common/templates/epel-mirrorlist

Mirror fedora-epel.mirror.lstn.net is almost a week out of date and
causing yum package transactions to fail due to bad repodata.  Replacing
with a mirror closer to the sepia and octo labs.
Fixes: http://tracker.ceph.com/issues/15539

common: Replace bad epel mirror

---

roles/pcp/tasks/collector.yml
roles/pcp/tasks/manager.yml
roles/pcp/tasks/permissons.yml

http://tracker.ceph.com/issues/15575
Some hosts were getting a /var/log/pcp/pmmgr that was owned by root:root
for some reason.

pcp: Correct /var/log/pcp permissions for collectors

---

roles/testnode/tasks/nrpe-selinux.yml

The 'nagios_run_sudo' boolean was added after RHEL7.1 GA.
Attempting to set the boolean when it's not present causes ansible
to fail.  NRPE will cause SELinux failures in test jobs unless set
so the only other option would be to disable NRPE on
RHEL/CentOS <= 7.1
This change ensures the testnode has the latest version of SELinux
policy installed, and thus, ensuring the boolean exists.

testnode: Update SELinux policy when configuring NRPE

---

roles/cobbler/templates/kickstarts/cephlab_ubuntu.preseed

"bootdev string default" is only supported in Xenial apparently.
Discovered this after attempting to install Trusty using the new kickstart.

cobbler: Only set bootdev in kickstart if installing Xenial.

---

roles/cobbler_profile/defaults/main.yml

systemd in Xenial was renaming NICs to `eno1`.
Since we ship a static `/etc/network/interfaces` file with `eth0` as the only NIC name, networking wouldn't come up on boot.
Tested on clara and magna node.

cobbler: Prevent systemd from renaming NICs

---

roles/testnode/tasks/main.yml

Fixes: http://tracker.ceph.com/issues/15675

testnode: Skip NRPE selinux setup if selinux disabled

---

roles/testnode/templates/nagios/nrpe.cfg

nagios monitoring still needs to be moved to the `common` role eventually but this should cut down on the noise .. mainly from irvingi06 and senta01.

testnode: Update nagios CPU load thresholds to be less strict

---

roles/testnode/files/libexec/smart.sh

smart.sh: default rc to 0 (saw false UNKNOWNs with non-raid)

---

roles/users/tasks/main.yml

When building images with edeploy, UID 1000 was being taken by a
"normal" user; we need to reserve this for the teuthology user.

users: Set UID_MIN to 1001

---

roles/cobbler/templates/snippets/cephlab_rc_local

- Instead of sleeping for 30 secs and hoping network is up, wait until we can
reliably ping the Cobbler host.
- Give ansible more time to run before wget's built-in 15min timeout is reached.  Otherwise ansible will still run and finish but the lockfile won't get touched.

cobbler: testnode post-install rc.local fixes

---

roles/gateway/README.rst
roles/gateway/defaults/main.yml
roles/gateway/files/openvpn.logrotate
roles/gateway/handlers/main.yml
roles/gateway/tasks/fail2ban.yml
roles/gateway/tasks/firewall.yml
roles/gateway/tasks/main.yml
roles/gateway/tasks/network.yml
roles/gateway/templates/f2b.jail.local.j2
roles/gateway/templates/f2b.service.j2
roles/gateway/templates/ifcfg.j2
roles/gateway/templates/resolvconf.j2
roles/gateway/vars/packages.yml

Tested on fresh CentOS 7.2 VM in RHEV.  To test the role and avoid IP conflicts, check out the wip-gw-networking branch from the secrets repo and change the following:
- In `ansible/inventory/sepia`, replace gw.sepia.ceph.com with the VM's internal IP under `[gateway]`
- In `ansible/secrets/gateway.yml`, change the `local` line in the OpenVPN server config to a free public IP (I used 8.43.84.133)
- In `ansible/secrets/gateway.yml`, change the `server` line in the OpenVPN server config to something like `server 172.21.50.0 255.255.255.0`
A RHEV VM is the only place the role can really be tested since no other machines are configured to be reachable from the WAN.
This should *not* be run on the existing OpenVPN server.
21JUN2016 EDIT: Now that we've moved the gw into RHEV, the role can be …

Network configuration for gateway role

---

roles/testnode/tasks/redhat/rhel_7.yml
roles/testnode/tasks/setup-centos.yml
roles/testnode/tasks/setup-fedora.yml

Fixes: http://tracker.ceph.com/issues/16455

testnodes: Disable firewalld service after reboot on RPM-based distros

---

roles/cobbler/templates/snippets/cephlab_rc_local

Console output with this change looks like:
[  OK  ] Started Postfix Mail Transport Agent.
[  OK  ] Started Crash recovery kernel arming.
[  OK  ] Created slice user-1000.slice.
==================================
Instructing Cobbler to run Ansible
==================================
[  OK  ] Created slice user-1100.slice.
Starting Time & Date Service...
[  OK  ] Started Time & Date Service.

cobbler: Output message indicating Ansible is running after firstboot

---

roles/testnode/vars/centos_7.yml
roles/testnode/vars/redhat_7.yml

perl-CPAN is required to install Amazon::S3 using the 'cpan' command

testnodes: Install perl-CPAN on yum systems

---

ansible.cfg

Increase timeout from 12s to 120s for ansible cmds
Signed-off-by: Vasu Kulkarni vasu@redhat.com

use 120s instead of default 12s for cmd timeout

---

callback_plugins/failure_log.py

We are seeing: "RepresenterError: cannot represent an object: pcp"

If a YAML error is hit, log the raw object

---

roles/testnode/vars/centos_6.yml
roles/testnode/vars/centos_7.yml
roles/testnode/vars/redhat_6.yml
roles/testnode/vars/redhat_7.yml

Stop installing the gperftools-devel package on testnodes, for the following reasons:
1. Ceph does not require gperftools-devel at runtime, so installing it unnecessarily just slows everything down at this point.
2. When we want to test newer builds of gperftools (say, from RHEL 7.3), if the corresponding "gperftools-devel" package is not available on the test node, then yum will fail the transaction.
(Additionally, gperftools-devel is no longer in EPEL 7, and it has moved to RHEL 7 Optional in RHEL 7.2 (https://bugzilla.redhat.com/1213879, https://access.redhat.com/errata/RHEA-2015:2293). The "epel" list is no longer the correct list for this package on redhat_7 and centos_7.)

testnode: drop gperftools-devel

---

roles/testnode/tasks/redhat/rhel_6.yml
roles/testnode/tasks/redhat/rhel_7.yml
roles/testnode/tasks/setup-centos.yml
roles/testnode/tasks/setup-fedora.yml
roles/testnode/tasks/yum/firewall.yml
roles/testnode/tasks/yum_systems.yml

iptables was recently found installed and running on a RHEL7 system.
Previous testnode playbook runs wouldn't catch this since it shouldn't
be installed in the first place.  This change ensures firewalld and
iptables are stopped on all RPM-based distros.
Fixes: http://tracker.ceph.com/issues/16809

testnode: Disable firewalld and iptables regardless of OS version

---

ansible.cfg

This will cause ansible to display timing information for tasks,
allowing us to see what's slow and potentially improve speed.
I've been using this locally for a while now. It's nice.

Use the profile_tasks plugin

---

roles/teuthology/tasks/setup_users.yml

To be merged with https://github.com/ceph/ceph-sepia-secrets/pull/145

teuthology: Create tkill group and grant tkill_users right to run `kill`

---

roles/cobbler/templates/snippets/cephlab_packages_rhel
roles/common/README.rst
roles/common/defaults/main.yml
roles/common/tasks/beta_repos.yml
roles/common/tasks/yum_systems.yml

Combine with ceph-octo-secrets PR# 77
Tested on RHEL7.2 and RHEL7.3 using stock cobbler images.  RHEL7.2 gets subscribed to CDN as it should and RHEL7.3 uses the internal repos.  Also tested CentOS 7.2 for sanity and to verify `redhat-lsb-core` package is available.
`no_log: true` is ignored (https://github.com/ansible/ansible/issues/11253) for now but since logs are internal, it's not a big deal.  The only 'sensitive' info that gets output is the internal repo path.

Add support for testing RHEL beta distros using internal repos

---

roles/common/defaults/main.yml

The incorrect default causes ceph-cm-ansible to fail every teuthology job: 'with_dict expects a dict'
Signed-off-by: Josh Durgin <jdurgin@redhat.com>

defaults: beta_repos must be a dict

---

roles/users/tasks/create_users.yml

This change is mainly so the users role can be run on vps_hosts.
Previously, in order to update the ubuntu user's authorized_keys on
vps_hosts, the testnodes role had to be run which caused ubuntu to be
removed from the libvirtd group.
The ubuntu user is in managed_admin_users on vps_hosts so this will
ensure the user is added to sudo and left in the libvirtd group.
managed_users, on the other hand, we want to make sure are only in
groups we specify so the "Create all users without sudo access." task is
left as-is (without append: yes).
Combine with https://github.com/ceph/ceph-sepia-secrets/pull/160

users: Leave managed_admin_users' other group memberships alone

---

tools/vmlist.py

'virsh -r' allows vmlist.py to work with RHEV hypervisor hosts

Add vmhosts to vmlist.py and run virsh in read-only mode

---

roles/common/tasks/rhel-entitlements.yml
roles/common/tasks/yum_systems.yml

Tested on:
RHEL7.3 Beta
- Unregistered
RHEL7.3 RC2
- Unregistered
RHEL7.2
- Unregistered
- Already registered with expected repos from `rhsm_repos`
- Already registered with additional repos not in `rhsm_repos`
It was recently discovered that Release Candidate ISOs of RHEL don't output "Beta" or
"Alpha" in `lsb_release` output.  Therefore, RHEL RC Distros were
registering with CDN and not putting beta_repos in place.
This new method registers every RHEL system with CDN, checks if there are
any available matching repos based on ansible_distribution_version, and
either:
- Unregisters from CDN and runs beta_distros.yml if there are no CDN repos
- Continues with setting up desired rhsm_repos
I also added some additional working to task descriptions to hopefully
claer up what's going on in …

common: Change method of detecting beta distro

---

users.yml

This is needed if the users role is called manually.  Typically it's
called via the common role and "become: true" is inherited.
But in the case of just needing to update update the teuthology_user's pubkeys with @all.pub, just calling the users role manually is quicker.  sudo access is obviously required to modify users and groups.
Just tested by running `ansible-playbook users.yml --limit="vps_hosts"`

Use "become: true" for users role

---

roles/testnode/defaults/main.yml
roles/testnode/tasks/apt/repos.yml

Tested using ansible v2.2 on a smithi running Ubuntu 14.04, a smithi running CentOS 7.2, and a magna running RHEL 7.2.
`roles/testnode/vars/yum_systems.yml` isn't included on playbook runs where `ansible_pkg_mgr != apt`.  Even though the tasks relying on those vars are skipped, the tasks were still fatally failing because the vars weren't defined.  Defining empty defaults gets around that.

testnode: Define a few empty variables for ansible v2.2 compatibility

---

roles/downstream-setup/defaults/main.yml
roles/downstream-setup/tasks/main.yml

Vasu started seeing errors about `repos_to_remove` not being defined after we un-pinned Ansible from 2.1.  This goes back to the issue where task files that aren't even included or run are still being evaluated.  If they don't have empty variables set, the playbook fails.
So I defined an empty list for the var but was still getting:
`FAILED! => {"failed": true, "msg": "{{ repos_to_remove.split(',') }}: 'list object' has no attribute 'split'"}`
I found https://github.com/ansible/ansible/issues/18483 and have set both `setup.yml` and `cleanup.yml` when conditionals to be evaluated dynamically in https://github.com/ceph/ceph-cm-ansible/commit/adbc0903d3944d850be643e1a6dab169090eab7b
Fixes: http://tracker.ceph.com/issues/17922

Updates to downstream_setup role

---

roles/testnode/vars/ubuntu_16.yml

Fixes: http://tracker.ceph.com/issues/18067

testnode: Install libtool-bin for building xfstests

---

roles/teuthology/templates/nginx.conf

Gzipped files were being served as text/plain. Instead of applying text/plain to everythincg, extend the default MIME configuration to serve *.log as text/plain.

teuthology: Correct MIME type spec for log files

---

roles/testnode/tasks/ntp.yml

It's buggy (see comment in code) and we don't need it, because
teuthology does what it would do anyway.  Supposed to be fixed in
a later version of the Debian package which is in Yakkety.
Fixes: http://tracker.ceph.com/issues/18837

testnode/tasks/ntp: remove '/etc/network/if-up.d/ntpdate' on Xenial

---

roles/common/tasks/nrpe-selinux.yml

Jobs were occasionally failing due to
/etc/selinux/targeted/active/modules/400/mod_fastcgi/lang_ext being
corrupt.  mod_fastcgi is removed and reinstalled with every
testnodes.yml run anyway so this just makes sure valid SELinux policy
modules are put in place.
Fixes: http://tracker.ceph.com/issues/19126

common: Delete leftover SELinux policy modules

---

roles/common/tasks/nrpe-selinux.yml

This ensures module file integrity so we can build the nrpe selinux
module in the proceeding tasks.
Fixes: http://tracker.ceph.com/issues/19126

common: Reinstall selinux-policy-targeted if needed

---

roles/common/tasks/kerberos.yml

This is the first apt transaction that gets run in the common role.
Fixes: http://tracker.ceph.com/issues/15439

common: Clean apt cache before updating it

---

roles/common/tasks/main.yml

Prior to ansible v2.2.2.0, if the first conditional (`selinux_status is defined` in this case) was false, the second
conditional wasn't checked.
This change makes sure nrpe-selinux is only included on RHEL/CentOS
which are the only OSes that will have stdout for the selinux_status
var.
Successfully tested cephlab.yml run on
smithi202 - Xenial
smithi163 - Trusty
smithi032 - CentOS 7.3

common: Workaround for ansible bug conditional evaluation

---

roles/common/tasks/rhel-entitlements.yml

Seeing intermittent `subscription-manager unregister` failures in Octo.
Since the register task has retries, I see no reason unregistering
can't.

common: Retry unregister beta distro from CDN

---

roles/testnode/tasks/apt/repos.yml
roles/testnode/tasks/apt_systems.yml
roles/testnode/vars/ubuntu.yml
roles/testnode/vars/ubuntu_14.yml
roles/testnode/vars/ubuntu_16.yml

This all started as just needing to add a custom repo to Xenial to fix http://tracker.ceph.com/issues/18126
Then I noticed that `apt/repos.yml` tasks were never getting run on Xenial testnodes and some of those tasks are important.  This explains why https://github.com/ceph/teuthology/pull/1034 and https://github.com/ceph/teuthology/pull/1032 were needed.  Those can be reverted once this PR is merged.

Repo changes for Ubuntu testnodes

---

roles/public_facing/tasks/download.ceph.com.yml
roles/public_facing/tasks/letsencrypt_nginx.yml
roles/public_facing/tasks/www.ceph.com.yml

Discovered www.ceph.com was hitting this problem as well ever since an IPv6 address was added.  Makes sense to move it to a separate playbook at this point.

public_facing: Create separate task yml for letsencrypt/nginx/ipv6 hosts

---

roles/testnode/tasks/zap_disks.yml

Fixes bug introduced in https://github.com/ceph/ceph-cm-ansible/pull/323
The version of wipefs shipped with Trusty lacks the --force flag

testnode: Try wipefs without --force if flag is missing

---

roles/common/templates/nagios/nrpe.cfg

I can't find the exact commit in nrpe that caused this to change but the
path has changed and the nrpe service fails to start on CentOS/RHEL now.

common: Change path to nrpe pid_file on RedHat/CentOS

---

roles/testnode/tasks/main.yml

Fixes: http://tracker.ceph.com/issues/20623

testnodes: Clean up leftover Ceph artifacts from previous jobs

---

roles/cobbler/templates/snippets/cephlab_packages_rhel

Apparently doesn't come stock with CentOS 7.4 which was causing the
Cobbler ansible-playbook post-install run to fail.

cobbler: Install ntp package on RHEL/CentOS during kickstart

---

roles/testnode/tasks/main.yml

I moved lvm.conf in https://github.com/ceph/ceph-cm-ansible/pull/342
because I wanted all the disk management tasks clustered together.  I
failed to take into account the fact that the lvm2 package might not be
installed yet (like on OVH nodes).

testnode: Shuffle tasks around to make sure packages install first

---

roles/nameserver/tasks/config.yml

I observed an unintentional DoS on ns1.front last night right as most of
the nightly scheduled jobs started up.  Lots of "nf_conntrack: table
full, dropping packet" messages in the syslog.
Doubling it should be safe.

nameserver: Double max amount of concurrent connections

---

roles/testnode/tasks/main.yml

Example:
```
changed: false
cmd: "find /var/run/ -name \"*ceph*\""
delta: "0:00:00.004976"
end: "2017-09-29 18:42:23.050412"
failed: true
failed_when_result: true
item: /var/run/
rc: 1
start: "2017-09-29 18:42:23.045436"
stderr: "find: File system loop detected; '/var/run/rpc_pipefs/gssd' is part of the same file system loop as '/var/run/rpc_pipefs'."
stderr_lines: 
- "find: File system loop detected; '/var/run/rpc_pipefs/gssd' is part of the same file system loop as '/var/run/rpc_pipefs'."
stdout: ""
stdout_lines: []
```

testnode: Avoid job failure due to fs loop

---

roles/testnode/tasks/var_lib.yml

We've been seeing a lot of this:
http://tracker.ceph.com/issues/21989
I believe the issue is the XFS filesystem being created by tools that default to a version 5 superblock - a version too new for some of our testing kernels.
This is not widely tested - we can talk about it when you're back

testnode: Avoid an unmountable /var/lib/ceph

---

roles/vmhost/tasks/libvirt.yml

With a recent update to ansible, the changed task would never return a
'failed' result with `failed_when` set.  `ignore_errors` is what we want
so the task fails but the playbook proceeds.

vmhost: Allow task to fail but ignore errors

---

roles/cobbler/templates/snippets/cephlab_rc_local

This is for use with FOG.  When we create an OS image, the image
inherits the testnode's hostname that was used to create the image.
This rc.local snippet will make sure the testnode's hostname is set to
whatever the IP's PTR record is on every boot.
`rclocal_nameserver` should be set in the inventory groupvars.

cobbler: Add logic to rc.local for FOG-provisioned machines

---

roles/cobbler/templates/kickstarts/cephlab_ubuntu.preseed

ethtool is used in the new rc.local hackery

cobbler: Install ethtool on reimage

---

roles/cobbler/templates/snippets/cephlab_rc_local

In case the system has multiple NICs cabled (like Octo's bruuni and
pluto)

cobbler: Don't break after first NIC is configured

---

roles/cobbler/templates/snippets/cephlab_rc_local

An issue was discovered where rc.local bails if a testnode has multiple
NICs cabled but each NIC doesn't have a DHCP reservation.  For example,
some of the magnas have a second NIC cabled but are cabled to a tagged
port on the switch so they can pass traffic via multiple VLANs.
Fixes: http://tracker.ceph.com/issues/22651

cobbler: Remove DHCP config for NICs if ifup fails in rc.local

---

roles/cobbler/templates/kickstarts/cephlab_rhel.ks

I concede.  Name it whatever you want, RHEL.
This will allow the OS to use the "predictable naming" during anaconda
and after firstboot preventing NIC names from switching like we're
seeing in http://tracker.ceph.com/issues/22732 and http://tracker.ceph.com/issues/22643

cobbler: Use MAC address specified in ansible inventory instead of eth0

---

roles/nameserver/tasks/records.yml

It takes about 3 minutes for ansible to compile all the zone files.
That was causing nsupdate/DDNS to overwrite any new records we wanted to
add or change before named could be reloaded.
This PR:
- Writes zone files to a temporary location
- Dumps pending DDNS changes into zone files
- Freezes DDNS zone files from updates
- Moves temporary zone files into place all at once
- Unfreezes DDNS zone files
This results in about a 3 second window where DDNS updates will be
refused which isn't great but we can at least update records while OVH
jobs are running now.

nameserver: Let records tasks coexist with DDNS

---

roles/cobbler/templates/snippets/cephlab_rc_local

This PR is mainly needed for the bruuni and pluto systems in the downstream lab.
Those systems have two NICs cabled.  One to the front network and one to a private 10Gb switch.  Both networks have DHCP and both NICs have static reservations.
What was happening was the main uplink NIC would get its DHCP config written and then the second/private NIC would overwrite it.
This PR ensures only the uplinked NIC's config gets written by making sure the host can ping our cobbler server (`$http_server`).
The second/private NIC's config gets written by `testnodes/tasks/secondary_nic.yml`

More rc.local NIC fixees

---

roles/common/tasks/rhel-entitlements.yml

subscription-manager throws an error now if there are no releases to list
for a subscribed Beta distro.

common: Tolerate new subscription-manager behavior

---

roles/cobbler/templates/snippets/cephlab_rc_local

DHCP might not complete within that one second.  We'll relax the timeout
a bit.

cobbler: Allow a little leeway in rc.local when pinging http_server

---

roles/testnode/README.rst

testnode: Fix typo and clarify dict for drives_to_partition

---

roles/cobbler/templates/snippets/cephlab_rc_local

I've observed a *very* occasional race condition where dhclient
completes but the host can't ping Cobbler.  Instead of timing out
waiting for one ping packet to return, we'll try pinging X number of
times (based on $attempts number) and then give up.
Example of old behavior:
```
+ echo -e 'auto lo\niface lo inet loopback\n\nauto enp3s0f1\niface enp3s0f1 inet dhcp'
+ ifdown enp3s0f1
Killed old client process
Internet Systems Consortium DHCP Client 4.3.3
Copyright 2004-2015 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/
Listening on LPF/enp3s0f1/0c:c4:7a:8f:ce:7f
Sending on   LPF/enp3s0f1/0c:c4:7a:8f:ce:7f
Sending on   Socket/fallback
DHCPRELEASE on enp3s0f1 to 172.21.0.10 port 67 (xid=0x492dda3e)
+ set +e
+ ifup enp3s0f1
Internet …
```

cobbler: Change method used to ping Cobbler host in rc.local

---

roles/cobbler/templates/snippets/cephlab_rc_local

This covers all baremetal types except mira.  Cheetah/Cobbler templating
was breaking with commit
https://github.com/ceph/ceph-cm-ansible/pull/389/commits/de871c037f4ae227bed00933eee24f849a4551b0.
The problem is if there is more than one kernel option type (like
console, ksdevice, etc.), $kernel_options gets expanded into a json
dictionary and breaks the templating.
E.g., {'ksdevice': 'bootif', 'lang': ' ', 'console': ['tty0', 'ttyS1,115200'], 'text': None, 'netcfg/choose_interface': 'auto'}
Rather than fight with that, we'll just output to ttyS1.

cobbler: Just output to ttyS1

---

roles/testnode/tasks/configure_lvm.yml

This was actually happening because when the playbook first runs, the
setup module is run and sees the device mapper devices.  We zap them
later in the playbook but ansible doesn't know that.  We could just
re-run the setup module but this method will instead guarantee we don't
use dm-* devices.
Fixes: https://tracker.ceph.com/issues/23845

testnode: Exclude dm devices from list of physical volumes

---

roles/common/tasks/yum_systems.yml
roles/testnode/tasks/yum_systems.yml

`skip_entitlements` and `skip_packaging` will be set to true in the
Ansible inventory for OVH nodes

common/testnode: Support skipping entitlements & packages

---

roles/cobbler/templates/kickstarts/cephlab_rhel_sdm.ks
roles/cobbler/templates/kickstarts/cephlab_ubuntu_sdm.preseed

The root drive on mero nodes is /dev/sdm.  Since Cobbler is only used to
provision testnodes prior to a FOG image capture, I didn't think it'd be
worth the time/effort to automate this further.
The kickstart will have to be manually selected if the Cobbler Web UI is
used.  I'll automate setting the kickstart when the octo-fog-images
Jenkins job runs.

cobbler: Add kickstarts that will install to /dev/sdm

---

roles/cobbler/templates/snippets/cephlab_rc_local

Before this change, if the first NIC on a machine had a link but wasn't
the uplinked NIC, the break would still get called and no NICs would be
left up.
Now we'll break only after we can ping the Cobbler host.

cobbler: break at the appropriate location in rc.local

---

roles/public_facing/templates/f2b_ufw.conf.j2

UFW requires the protocol be specified when multiple ports are given for
a deny rule.

public_facing: Support blocking multiple ports in ufw fail2ban action

---

roles/cobbler/templates/kickstarts/cephlab_ubuntu.preseed
roles/cobbler/templates/kickstarts/cephlab_ubuntu_sdm.preseed

I replaced wget with curl in rc.local because curl is installed by
default in RPM-based distros while wget isn't even available for RHEL8
(yet?).  It apparently is not installed by default in Ubuntu though so
we'll install it during kickstart.

cobbler: Install curl during Ubuntu kickstart

---

roles/testnode/vars/centos_7.yml
roles/testnode/vars/redhat_7.yml

Fixes: https://tracker.ceph.com/issues/35989

testnode: install gcc-c++ on RPM-based systems

---

roles/cobbler/templates/snippets/cephlab_packages_rhel

This package is needed for ceph-mgr but is not available in the
base/default repos.  Therefore, we need to install it during kickstart
and bake it into our RHEL FOG images.
Fixes: https://tracker.ceph.com/issues/36653

cobbler: Install python-jwt on RPM-based testnodes

---

ansible_managed.yml
cephlab.yml
roles/cobbler/templates/snippets/cephlab_packages_rhel
roles/cobbler/templates/snippets/cephlab_rc_local
roles/cobbler/templates/triggers/install/post/cephlab_ansible.sh
roles/common/tasks/kerberos.yml
roles/common/tasks/main.yml
roles/common/tasks/nagios.yml
roles/common/tasks/rhel-entitlements.yml
roles/common/tasks/yum_systems.yml
roles/common/vars/redhat_8.yml
roles/testnode/tasks/main.yml
roles/testnode/tasks/yum/packages.yml
roles/testnode/tasks/zap_disks.yml
roles/testnode/templates/ssh/sshd_config_redhat_8
roles/testnode/vars/dnf_systems.yml
roles/testnode/vars/redhat_8.yml
set_python_path.yml

- `libselinux-python, libsemanage-python, policycoreutils-python, ntp, python-jwt` are not available in RHEL8 so they're skipped in the `cephlab_packages_rhel` snippet.
- Replaced `wget` with `curl` in `snippets/cephlab_rc_local` since curl is universally available and installed by default.  At the time I first started working on these changes, wget wasn't packaged for RHEL8 yet.
- `s/ansible_pkg_mgr/ansible_os_family` - `ansible_pkg_mgr` was skipping a lot of tasks because `ansible_pkg_mgr=dnf` for RHEL8.
- `s/yum:/package:` - `package` is a package-manager-agnostic module that will use dnf or yum.
- In `rhel-entitlements.yml`, the `Register with subscription-manager.` task would return 0 but there aren't any RHEL8 repos in RHSM yet.  So the play doesn't successfully identify the OS as …

Add RHEL8!

---

roles/cobbler/templates/kickstarts/cephlab_rhel.ks
roles/cobbler/templates/kickstarts/cephlab_rhel_sdm.ks

Requested by downstream QE.  This shouldn't be an issue since only
downstream QE needs SELinux in Enforcing mode.  They don't use
ceph-cm-ansible which sets it to Permissive in the testnodes role.
Fixes: http://tracker.ceph.com/issues/37338

cobbler: Set SELinux = enforcing by default

---

roles/testnode/tasks/resolvconf.yml

resolvconf isn't installed on Bionic by default so we don't need to
bounce the interface to work around the bug.
Fixes: https://tracker.ceph.com/issues/37614

testnode: Only bounce interface on Xenial

---

roles/cobbler/templates/snippets/cephlab_packages_rhel

We need to check for RHEL or CentOS

cobbler: Fix RPM snippet conditional

---

roles/common/tasks/yum_systems.yml

In some instances, the mira still hadn't rebooted before wait_for_connection ran.
Example: http://qa-proxy.ceph.com/teuthology/laura-2019-02-13_13:30:43-rados:mgr-wip-lpaduano-testing-26325-distro-basic-mira/3584174/teuthology.log

common: After reboot, wait longer before polling for connection

---

roles/long_running_cluster/tasks/logrotate.yml

The scheduled logrotate cronjob at 06:25 doesn't actually get run like I assumed.  This is because the cron.daily job doesn't use -f.

long_running_cluster: Force logrotate at 06:25

---

roles/common/vars/redhat_8.yml

The RHEL 8 beta is GPG-signed, so we might as well verify signatures.

add GPG checking for RHEL 8

---

roles/teuthology/tasks/main.yml

The beanstalkd service should be running before any
try to start workers up

teuthology: make sure beanstalkd is running

---

roles/common/vars/redhat_8.yml

The RHEL 8 beta is signed with the beta key, not the GA key.

RHEL 8 uses Red Hat's beta key

---

roles/long_running_cluster/templates/ceph-common.logrotate

I guess the logrotate config was updated in the actual Ceph packages at some point so I'm updating this template to match.
Also, we need to keep fewer logs because the reesi keep filling up.

long_running_cluster: Keep fewer logs & update postrotate

---

roles/cobbler/templates/snippets/cephlab_rhel_disks

Syntax was incorrect and caused issues on systems where /dev/sda isn't the first disk in the system.

cobbler: Update RHEL disk partition snippet for RHEL8

---

roles/cobbler_profile/defaults/main.yml

The copy of the image wore too old to work with kickstart

Updating ISO Image for Ubuntu-16-04

---

roles/testnode/vars/centos_7.yml
roles/testnode/vars/redhat_7.6.yml
roles/testnode/vars/redhat_7.yml

Downstream QE was seeing an issue where a newer version of a package was required but the version in lab-extras was being pinned because the priority was set to high.
IMO, we should be letting whichever repo (regardless of source) install the latest package(s).

testnode: Don't set priority for additional repos

---

roles/common/tasks/nrpe-selinux.yml

Not only are we not using pcp anymore but we also reimage machines before every job so they modules can't get corrupt in the first place.

common: Don't mess with pcp selinux modules

---

roles/cobbler/templates/snippets/cephlab_rc_local

Behavior changed in RHEL8.  See example below.
```
+ ifdown enp3s0f1
Error: '/etc/sysconfig/network-scripts/ifcfg-enp3s0f1' is not an active connection.
Error: no active connection provided.
```
Then the script would quit.

cobbler: Allow ifdown to fail during rc.local

---

roles/users/README.rst
roles/users/defaults/main.yml
roles/users/tasks/main.yml

I'd like some input on this.
1) Is there a better way to do https://github.com/ceph/ceph-cm-ansible/compare/wip-skip-users?expand=1#diff-9ac36c3dbec0caf35aa4369ba60b54bdR20-R29
2) I couldn't find an ansible module to do https://github.com/ceph/ceph-cm-ansible/compare/wip-skip-users?expand=1#diff-9ac36c3dbec0caf35aa4369ba60b54bdR15 better than just `cat`ing the file.  Did I miss something?  `slurp:` didn't do what I wanted.
3) Am I missing any edge cases where this could go wrong?  I tried to get it so that if there are any problems with `git` locally or reading the sentinel file that the tasks would still run.
As long as we keep the FOG images up to date when we add new lab users, this would save a minute per testnode per job.

users: Tasks to allow skipping of role if all users/keys are already up to date

---

cobbler.yml
roles/cobbler_profile/defaults/main.yml
roles/testnode/vars/redhat_7.8.yml

A separate `packages` list was required because podman and libev-devel are missing (from the beta at least).

cobbler: Add RHEL7.8

---

roles/users/tasks/main.yml

TIL `connection: local` != `delegate_to: localhost`
See https://github.com/ansible/ansible/issues/16724#issuecomment-259989010

users: delegate task to localhost

---

roles/common/templates/epel-mirrorlist
roles/common/templates/epel-testing-mirrorlist

These mirrors are in the Community Cage (where Sepia is) so they should speed yum transactions up a bit.

common: Add a couple closer mirrors

---

roles/common/tasks/epel.yml

common: rm yum cache that doesn't get cleaned yum `yum clean`

---

tools/roles/generate-fog-csv/templates/csv.j2

generate-fog-csv: Support setting alternate 'Host Primary Disk' in FOG

---

roles/cobbler_profile/defaults/main.yml

This prevents the installer from pausing to ask for the install media

cobbler: Set kernel_options for OpenSUSE distros

---

roles/testnode/vars/centos_8.yml
roles/testnode/vars/redhat_8.yml

Needed for package-cleanup, which is used by the kernel task.

testnode: install dnf-utils on el8

---

roles/testnode/vars/centos_8.yml

This is until the python3-tempora package is fixed

temporarily require python3-pytz

---

roles/testnode/vars/centos_8.yml
roles/testnode/vars/redhat_8.yml

python3-tempora is now fixed to require this.

testnode: el8: drop python3-pytz dep

---

roles/testnode/vars/centos_7.yml
roles/testnode/vars/redhat_7.yml

Need this for el7 nodes too--anywhere we run cephadm.

testnode: el7: install podman-docker

---

roles/cobbler/templates/triggers/install/post/cephlab_ansible.sh

Both cobbler hosts (cobbler.front.sepia.ceph.com and magna001.ceph.redhat.com) are now running versions of ansible that handle python interpreter discovery automatically.
Setting this manually was actually causing issues because some ceph-cm-ansible tasks get delegated to localhost (Like 'Clone the keys repo' in the Users role).  So when setting -e ansible_python_interpreter=/usr/bin/python3, ansible looks for that binary on the localhost.  magna001 doesn't have python3 so the playbook run would fail.

cobbler: Don't set ansible_python_interpreter manually anymore

---

roles/testnode/tasks/yum/packages.yml

This will stop all the RHEL8 failures.

testnode: Workaround for BZ 1782899

---

roles/testnode/vars/redhat_8.yml

Octo lab doesn't use epel by default but by moving this package to `epel_packages`, it will get installed during this task: https://github.com/ceph/ceph-cm-ansible/blob/master/roles/testnode/tasks/yum/packages.yml#L58

testnode: Move dbench to epel_packages so it gets installed

---

roles/common/vars/centos_8.yml
roles/common/vars/redhat_8.yml

Honestly not even sure how this was working at all but in order for https://github.com/ceph/ceph-cm-ansible/pull/487 to work, the repo file needs to actually point to upstream epel to refresh the yum metadata.

common: Add baseurl to epel repo files

---

roles/common/tasks/epel.yml
roles/common/vars/centos_8.yml
roles/common/vars/redhat_8.yml

So here's the order of events that caused all the epel issues over the past year or so.
1. CentOS/RHEL 8 came out and I created a separate `epel_repos` var that used `metalink` instead of `mirrorlist`.  This was because the URL was slightly different (addition of `/Everything/` dir).
2. We saw intermittent 404 errors attempting to update epel metadata.
3. I added baseurl and some tasks to force yum to update the metadata from the upstream/official epel repo
4. We still continued to see occasional errors updating metadata
5. I added some jinja2 to add `/Everything/` to the baseurl and metalink URLs but we continued to see random yum failures
6. I realized (today) that we resolved all these errors in the past by using a mirrorlist and that's not what we're doing in RHEL/CentOS8 so I'm …

Use epel mirrors

---

roles/cobbler_profile/defaults/main.yml

The Ubuntu installer appears to at least probe non-root disks during the `update-grub` step.  This was hanging on LVs leftover from previous installations on the smithi NVMe drives.
Settings this kernel option fixes it.
See https://bugs.launchpad.net/ubuntu/+source/debian-installer/+bug/1854839/comments/2

cobbler_profile: Disable OS prober to prevent update-grub hang

---

roles/cobbler/templates/snippets/cephlab_packages_rhel

Changes:
- @infrastructure-server group name change
- perl and redhat-lsb-core aren't available in Fedora 31 apparently
- Added some comments for clarity

cobbler: Update snippet for clarity and Fedora 31

---

roles/cobbler/templates/snippets/cephlab_packages_rhel

Let's just hope the basic packages we'd need to at least get ceph-cm-ansible running exist in the base Fedora 31 DVD image.
We can't figure out the @base -> @infrastructure-server-environment -> @???? group name progression/changes so forget it.

cobbler: More kickstart adjustments for Fedora 31

---

roles/testnode/vars/opensuse_leap_15.2.yml

We should not be using Python 2 at all...
Signed-off-by: Nathan Cutler <ncutler@suse.com>

testnode: use Python 3 in openSUSE Leap 15.2

---

roles/testnode/README.rst
roles/testnode/tasks/yum/repos.yml
roles/testnode/templates/mirrorlists/8/CentOS-AppStream-mirrorlist
roles/testnode/templates/mirrorlists/8/CentOS-Base-mirrorlist
roles/testnode/templates/mirrorlists/8/CentOS-Extras-mirrorlist
roles/testnode/vars/centos_8.yml

Fixes ``Failed to download metadata for repo 'extras'`` errors.

testnode: Use mirrorlists for CentOS 8 repos

---

roles/common/defaults/main.yml

Despite having a mirrorlist present in the repo file, if contacting the baseurl fails, the yum transaction fails which causes our jobs to fail.  Let's try *just* using a mirrorlist.
See https://github.com/ceph/ceph-cm-ansible/pull/542#issuecomment-598924481

common: Don't use baseurl for epel at all

---

roles/nameserver/templates/named.conf.j2

nameserver: Support python2 and python3 in named.conf template

---

roles/nameserver/tasks/config.yml

nameserver: Configure selinux only if enabled

---

roles/nameserver/tasks/main.yml
roles/nameserver/vars/empty.yml

secrets/nameserver.yml is only required if we're using DDNS

nameserver: Don't require secrets

---

roles/nameserver/README.rst
roles/nameserver/templates/named.conf.j2

When setting up this nameserver role in Octo, recursive lookups were failing.  I suspect maybe BIND is doing an `NS` lookup when it doesn't know about a domain it is asked about.  Red Hat blocks all external DNS queries so I've defined an internal DNS server for the Octo BIND server to forward to.  Now external lookups work.

nameserver: Support forwarders

---

roles/cobbler_systems/tasks/populate_systems.yml

We must have some systems that snuck into cobbler without having a MAC or IP so when this second "update" task runs, it fails

cobbler_systems: Only update systems if mac and ip are defined

---

roles/testnode/vars/centos_8.yml
roles/testnode/vars/redhat_8.yml
roles/testnode/vars/yum_systems.yml

The iozone package is remove from centos/rhel 8 dues to the license
issue, and this will install the package from the spia lab repo.
Fixes: https://tracker.ceph.com/issues/43600
Signed-off-by: Xiubo Li <xiubli@redhat.com>

testnode: install iozone package from sepia lab repo

---

roles/testnode/tasks/pip.yml

Apparently ansible is smart enough to figure this out on CentOS/RHEL8 (python3 distros) but not Ubuntu Focal.  So when I manually set the vars for a python3 distro and only included Fossa, it broke CentOS8.

testnode: Fix pip vars for CentOS/RHEL8

---

roles/testnode/templates/mirrorlists/8/CentOS-AppStream-mirrorlist
roles/testnode/templates/mirrorlists/8/CentOS-Base-mirrorlist
roles/testnode/templates/mirrorlists/8/CentOS-Extras-mirrorlist

I think there used to be individual directories with the ansible_lsb.release in the path but now there only seems to be "8" and "8.1.1911" so we'll just use 8.

testnode: Fix CentOS repo mirrorlists

---

roles/testnode/tasks/yum/packages.yml
roles/testnode/vars/centos_8.yml
roles/testnode/vars/redhat_8.yml

These groups are already taken care of during Cobbler installation.  We're hitting https://bugzilla.redhat.com/show_bug.cgi?id=1782899 in RHEL8 so let's not bother trying to reinstall during ceph-cm-ansible.

testnode: Don't attempt to install base or core

---

roles/cobbler/templates/snippets/cephlab_rc_local

This would have been particularly useful before https://tracker.ceph.com/issues/45341 got fixed so I could say *definitively* that the NIC bouncing was to blame for job failures but it can't hurt to have it now.

cobbler: Print the date during rc.local

---

tools/generate-fog-csv.yml
tools/roles/generate-fog-csv/templates/csv.j2

There's some hosts that are "cobbler_managed" but don't have a MAC and don't need a MAC.  Ansible doesn't help us out any here and print WHICH host doesn't have a MAC.  Just throws an error.
Also, there's no need to gather facts on localhost so I set that to `false`

generate-fog-csv: Only print a line if the MAC is defined

---

roles/common/tasks/nagios.yml
roles/testnode/tasks/apt_systems.yml
roles/testnode/tasks/ntp.yml

Using the systemd ansible module doesn't help either
https://github.com/ansible/ansible/issues/36585
https://github.com/ansible/ansible/issues/22171

all: Ignore warnings about systemd failing to control init scripts

---

roles/common/handlers/main.yml
roles/testnode/handlers/main.yml

Follow-up to https://github.com/ceph/ceph-cm-ansible/pull/578
https://pulpito.ceph.com/teuthology-2020-07-15_15:18:26-smoke-octopus-testing-basic-smithi/

all: Ignore more warnings about systemd failing to control init scripts

---

roles/testnode/tasks/zap_disks.yml

We don't need zapping of libvirt dvd devices

testnode: don't zap 'sr' devices

---

roles/teuthology/templates/nginx.conf

in particular, gzip_static on allows the server to return file.gz
(if compression is allowable) for files that are requested as "file".
This handles the teuthology.log.gz files that are still referred to as
teuthology.log from pulpito pages.
Signed-off-by: Dan Mick <dmick@redhat.com>

teuthology nginx: add gzip_ variables to allow compressed responses

---

roles/testnode/vars/redhat_8.yml

The PSI nodes downstream don't have lvm2 pre-installed like the baremetal ISO image.

testnode: Install lvm2 on RHEL8 machines

---

roles/common/files/libexec/smart.sh

The SSDs in the bruuni don't really provide much useful detail once they've failed beyond a certain point.
```
[root@bruuni002 ~]# sudo smartctl -a /dev/sdb | grep -E "FAILED\!|$"
smartctl 7.1 2020-04-05 r5049 [x86_64-linux-4.18.0-240.1.1.el8_3.x86_64] (local build)
Copyright (C) 2002-19, Bruce Allen, Christian Franke, www.smartmontools.org
=== START OF INFORMATION SECTION ===
Model Family:     Intel S3520 Series SSDs
Device Model:     INTEL SSDSC2BB960G7
Serial Number:    XXXXXXX
LU WWN Device Id: 5 5cd2e4 14e0db4c1
Firmware Version: N2010112
User Capacity:    960,197,124,096 bytes [960 GB]
Sector Sizes:     512 bytes logical, 4096 bytes physical
Rotation Rate:    Solid State Device
Form Factor:      2.5 inches
Device is:        In smartctl database [for details use: -P show]
ATA Version …
```

smart.sh enhancements for totally failed drives

---

roles/testnode/README.rst
roles/testnode/tasks/filesystems.yml
roles/testnode/tasks/main.yml

Fixes: https://tracker.ceph.com/issues/6373
This will really only be useful is `drives_to_partition` or `logical_volumes` gets overridden in ansible.cephlab overrides in teuthology yaml.  e.g.,
```
overrides:
ansible.cephlab:
vars:
drives_to_partition:
nvme0n1:
device: "/dev/nvme0n1"
unit: "GB"
sizes:
- "0 80"
- "80 160"
- "160 240"
- "240 320"
- "320 340"
- "340 400"
scratch_devs:
- p1
- p2
- p3
- p4
filesystems:
nvme0n1p6:
device: "/dev/nvme0n1p6"
fstype: xfs
mountpoint: "/var/cache/fscache"
```

testnode: Basic filesystem and mountpoint support

---

roles/container-host/tasks/container_mirror.yml

Let's get rid of these consecutives `set_fact`.
We can inject `PATH` variable on the task calling `registries-conf-ctl`
instead.
Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

container-host: quick improvement in container_mirror code

---

roles/container-host/tasks/container_mirror.yml

Once the mirror has been added in `/etc/docker/daemon.json`
we need to restart the daemon.
This is not very elegant but it's a workaround for now.
Signed-off-by: Guillaume Abrioux <gabrioux@redhat.com>

container-host: restart docker service

---

roles/container-host/tasks/container_mirror.yml

container-host: Ignore service restart error on new kernel

---

roles/testnode/vars/redhat_8.yml

This package isn't included in the cloud image that the Octo PSI nodes use.
Fixes: https://tracker.ceph.com/issues/48751

testnode: Install make on el8

---

roles/container-host/README.rst
roles/container-host/tasks/container_mirror.yml
roles/container-host/tasks/main.yml
roles/container-host/vars/main.yml

Fixes: https://tracker.ceph.com/issues/48715

container-host: Install mirror cert in both podman and docker paths

---

roles/users/defaults/main.yml
roles/users/tasks/update_keys.yml

This will allow one to run the users role prior to a PR being merged.

users: Support defining different branch

---

roles/testnode/vars/centos_8.yml

See https://bugzilla.redhat.com/show_bug.cgi?id=1828681
Signed-off-by: Jason Dillaman <dillaman@redhat.com>

testnode: libgcrypt needs to be updated to match QEMU build

---

roles/testnode/README.rst
roles/testnode/tasks/apt/packages.yml
roles/testnode/vars/ubuntu.yml

collectl has a bunch of Gnome Desktop Environment packages that are recommended.  So on Ubuntu 20.04 at least, a desktop environment was getting installed and would eventually go to sleep.

testnode: Install collectl without recommended packages

---

roles/cobbler_profile/tasks/import_distro.yml
roles/cobbler_profile/tasks/import_distro_image.yml
roles/cobbler_profile/tasks/import_distro_iso.yml

I guess something changed in ansible so that it doesn't like 'import' as the variable name.

cobbler_profile: s/import/imported

---

cobbler.yml
roles/cobbler/templates/triggers/install/post/cephlab_ansible.sh
roles/cobbler_profile/defaults/main.yml
roles/cobbler_profile/tasks/import_distro.yml
roles/cobbler_profile/tasks/import_stream_profile.yml
roles/testnode/tasks/yum/repos.yml
roles/testnode/templates/mirrorlists/8/CentOS-AppStream-mirrorlist
roles/testnode/templates/mirrorlists/8/CentOS-Base-mirrorlist
roles/testnode/templates/mirrorlists/8/CentOS-Extras-mirrorlist
roles/testnode/vars/yum_systems.yml
tools/convert-to-centos-stream.yml

We have to do it this way for a number of reasons
1. The vmlinuz and initrd in the CentOS Stream ISO aren't compatible. https://bugs.centos.org/view.php?id=18188
2. The version of Cobbler we're running does not recognize CentOS Stream ISO without hacking the distro_signatures file
3. Probably most importantly, when using the CentOS Stream ISO, after the installation is finished, we bizarrely end up with CentOS 8.3...  Not Stream.

cobbler: Support CentOS Stream

---

cephlab.yml
roles/testnode/tasks/main.yml

Now that we're running the entire cephlab.yml playbook during Cobbler kickstart, the sentinel file is getting touched while the container-host playbook is still running.
This change will still write the /ceph-qa-ready sentinel file during the testnodes role if the testnodes role got called directly

testnode: Write sentinel file after container-host role

---

roles/testnode/tasks/secondary_nic.yml

If the NIC was already down, `ifdown` causes the playbook to fail.  We want to always (at least attempt to) take the NIC down, then bring it back up.

testnode: Always ifup the secondary NIC

---

roles/testnode/vars/centos_8.yml

This usually gets installed via Cobbler during FOG image capturing.  That doesn't do us any good when FOG isn't being used.

testnode: Install redhat-lsb-core

---

roles/container-host/tasks/container_mirror.yml

This was needed on CentOS8 and Ubuntu Focal Jenkins builders.

container-host: Install pip too

---

roles/testnode/vars/centos_8.yml
roles/testnode/vars/redhat_8.yml

python3-asyncssh is not included by EPEL8 yet, but mgr-cephadm requires
it. see also https://tracker.ceph.com/issues/44676
Signed-off-by: Kefu Chai <tchaikov@gmail.com>

roles/testnode/vars: add ceph/python3-asyncssh to copr_repos

---

roles/testnode/vars/ubuntu_20.yml

since we are going to replace virtualenv with "python3 -m venv",
let's add python3-venv.
keep python3-virtualenv around for a while just in case.
Signed-off-by: Kefu Chai <tchaikov@gmail.com>

roles/testnode/vars/ubuntu_20: add python3-venv to packages

---

roles/long_running_cluster/tasks/logrotate.yml

cephadm manages a different logrotate file.  That file's name is the cluster FSID.
So I'll defined lrc_fsid in the secrets repo and this task will change the cronjob to run that logrotate file instead of the ceph-common one (that wasn't doing anything useful anyway).

lrc: Have logrotate cronjob optionally run the cephadm-created conf

---

roles/testnode/vars/ubuntu.yml

Fixes: https://twitter.com/letsencrypt/status/1443621997288767491
https://github.com/nodesource/distributions/issues/1266#issuecomment-931481002

testnode: Install libgnutls30 on Ubuntu systems

---

roles/testnode/tasks/yum/gpg_keys.yml
roles/testnode/tasks/yum/repos.yml
roles/testnode/vars/centos_7.yml
roles/testnode/vars/centos_8.yml
roles/testnode/vars/redhat_7.yml
roles/testnode/vars/redhat_8.yml

Some changes to Rados GW will require some dependencies in this repo.  See https://github.com/ceph/ceph/pull/40802

testnode: Add Apache Arrow repo

---

roles/container-host/tasks/container_mirror.yml
roles/container-host/vars/apt_systems.yml
roles/container-host/vars/centos_7.yml
roles/container-host/vars/ubuntu_18.yml

I need this role for Jenkins builders.  They don't get setuptools or pip installed during the common role.

container-host: Install python dependencies

---

roles/cobbler/templates/kickstarts/cephlab_rhel.ks
roles/cobbler/templates/kickstarts/cephlab_rhel_sdi.ks
roles/cobbler/templates/kickstarts/cephlab_rhel_sdm.ks

It occurred to me that the CentOS 8 Stream ISO is probably always going to be outdated so we can just run 'yum update' during kickstart.  We *don't* want to do this for non-Stream distro because it'll update a RHEL8.4 image to RHEL8.5, for example.

cobbler: Run yum update during CentOS Stream install

---

roles/container-host/tasks/main.yml

`container_packages` was getting set to `podman` for all downstream distros.  That won't work for Ubuntu so we'll use distro-specific secrets overrides.

container-host: distro-specific secrets file

---

roles/testnode/tasks/yum/gpg_keys.yml
roles/testnode/tasks/yum/repos.yml
roles/testnode/vars/centos_7.yml
roles/testnode/vars/centos_8.yml
roles/testnode/vars/redhat_7.yml
roles/testnode/vars/redhat_8.yml

This reverts commit 3f960fe1b6957bdfb551bd4e53ad275d0d446855.
the new plan is to submodule the things we needed from this repo, so it's no longer necessary. and since centos 8 eol, it looks like apache may have removed the `/centos/8/` repos so this is now causing teuthology failures

Revert "testnode: Add Apache Arrow repo"

---

roles/testnode/tasks/yum/stream.yml
roles/testnode/tasks/yum_systems.yml
roles/testnode/vars/centos_8_stream.yml
roles/testnode/vars/yum_systems.yml

Apparently the CentOS Stream Openstack images work despite the PXE images not working.
These changes are needed in order to run the testnode role against CentOS 8 Stream instances in Openstack.

testnode: Alternate method of detecting Stream (for Openstack instances)

---

roles/testnode/tasks/zap_disks.yml

This fixes an issue Seagate was hitting

testnode: Filter ansible_mounts with regex

---

roles/common/defaults/main.yml

common: failovermethod is deprecated

---

roles/testnode/vars/centos_8_stream.yml

I guess we were relying on a bug for the past few months. What would happen is centos_8.yml would get pulled in and the `packages` list got populated. Then later when we detect this is CentOS Stream, centos_8_stream.yml would get pulled in which overrode the original `packages` list.

testnode: Fix CentOS 8 Stream packages list

---

roles/common/tasks/rhel-entitlements.yml

For some reason, sometimes hosts try to register with their short hostname.  Sometimes with the FQDN.
As of Satellite 6.5, the service won't let you register two different hostnames with the same UUID (https://access.redhat.com/solutions/4207781).
This change makes sure all hosts register with the FQDN so there's no more conflicts.

common: RHSM register w/ full hostname

---

roles/testnode/tasks/apt_systems.yml

testnode: Skip stopping apache2 in containers

---

roles/cobbler_systems/defaults/main.yml

I just chose RHEL8.6 because it's available in both Sepia and Octo labs.  Ubuntu and CentOS aren't.

cobbler_systems: Set default_profile to a newer distro

---

roles/testnode/vars/ubuntu.yml
roles/testnode/vars/ubuntu_12.04.yml
roles/testnode/vars/ubuntu_14.yml
roles/testnode/vars/ubuntu_15.yml
roles/testnode/vars/ubuntu_16.yml
roles/testnode/vars/ubuntu_18.yml
roles/testnode/vars/ubuntu_20.yml

testnode: Move python-dev to distro-specific vars files

---

roles/cobbler/templates/snippets/cephlab_packages_rhel

cobbler: Don't install NetworkManager-initscripts-updown on CentOS9

---

tools/jenkins-builder-disk.yml

Used to wipe the larger/faster non-root drive on Jenkins builders and mount the disk at /home/jenkins-build or /var/lib/libvirt/images (whichever is appropriate).

tools: Add jenkins-builder-disk

---

roles/cobbler/templates/kickstarts/cephlab_rhel.ks
roles/cobbler/templates/kickstarts/cephlab_rhel_sdc.ks
roles/cobbler/templates/kickstarts/cephlab_rhel_sdi.ks
roles/cobbler/templates/kickstarts/cephlab_rhel_sdm.ks

We already run `subscription-manager` manually in kickstart so we don't need this snippet.

cobbler: Do not use redhat_register snippet

---

roles/testnode/tasks/cpan.yml

Using the cpanm ansible module instead of using the "command" module since we are seeing "Proceed nonetheless? [no] no', 'Aborted." during host re-imaging which can be solved using this module that does a clean installation in this case
http://pulpito.front.sepia.ceph.com/yuvalif-2022-12-20_21:29:08-rgw-wip-yuval-fix-58167-distro-default-smithi/7122795/

Using the cpanm ansible module

---

roles/gateway/templates/auth-openvpn

I chose to keep everything in binary throughout.  One could also choose string, but this seemed safer for international characters.
Signed-off-by: Dan Mick <dmick@redhat.com>

auth-openvpn: port to python3 for new gw server, futures

---

roles/common/tasks/rhel-entitlements.yml

Fixes: The DMI UUID of this host (XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX) matches other registered hosts
The "WA" stands for workaround, there is a bug in ansible "lineinfile" where it is replacing the double quotes with single quotes in the final outcome
And this workaround is doing the job

Regenerate random machine UUID before the subscribing to the satellite

---

roles/cobbler_profile/defaults/main.yml

Fixes: https://tracker.ceph.com/issues/58492

Changing centos9.stream image url to latest version for cobbler deployment

---

tools/checkcerts.py

This originally lived on gitbuilder-archive, and I've moved it, revamped it, added some args, added some hosts, modified some emails, ported to Py3, stopped using external programs.  It's quick to run in default mode where it just reports to the terminal; it'll also be quiet and only send email about old certs.
The timezone processing is nonexistent on the reported expiry date; Python timezone handling is a mess.  That could be improved but not without a deep dive.

Add checkcerts, to use with cron to warn about expiring certs

---

roles/paddles/tasks/setup_db.yml
roles/paddles/tasks/setup_docker.yml
roles/paddles/vars/apt_systems.yml

python-docker doesn't exist on 20.04; python3-docker does, and also on 18.04, and requires python3-requests.

paddles: Updates required for migration to new host

---

roles/common/defaults/main.yml

RHEL systems use `roles/common/tasks/rhel-entitlements.yml`, and this sets Yum's `$releasever` to a specific RHEL minor release (eg. `8.4` or `8.6`). As a result. Fedora's MirrorManager does not return any EPEL repositories for these minor RHEL versions.
We set a static `$releasever` in `rhel-entitlements.yml` so that we pin to old RHEL RPM content in our old RHEL nodes. We probably need to re-think this strategy since our CentOS Stream nodes do not (cannot) do this, and Red Hat does not really support pinning to old versions without an EUS subscription.
Rather than untangling all that and removing our `$releasever` manipulation altogether, this commit simply hard-codes `ansible_distribution_major_version` (`8`, `9`, etc) into the EPEL `.repo` files, ignoring `$releasever` for EPEL.
A …

common: use ansible_distribution_major_version in epel repos

---

cobbler.yml
roles/cobbler_profile/defaults/main.yml
roles/cobbler_profile/tasks/download_iso.yml

Discovered while trying to recapture a centos8.stream image

cobbler: Add CentOS 8.5, fix up obsolete get_url parameter

---

roles/cobbler/templates/triggers/install/post/cephlab_ansible.sh

cephlab_ansible.sh runs at the very end of the installation process during a cobbler install for fog image capture, on first reboot of the freshly-cobblered system.
Cobbler runs on a CentOS 7 installation today, but its python is too old to support modern ansible.  The SCL for python 3.8 is installed on cobbler.  Add code here to, if installed, enable the SCL (by setting some paths in the trigger script that is executed on the cobbler server after the installed host reboots; a curl fetch is placed at the end of /etc/rc.local, and this script runs to finish up all the configuration of the host for teuthology use.

cephlab_ansible.sh: use scl rh-python38 on CentOS 7

---

.ansible-lint
.github/workflows/tests.yml
roles/cobbler/tasks/settings.yml
roles/firmware/tasks/areca/main.yml
roles/firmware/tasks/mira/bios.yml
roles/firmware/tasks/mira/bmc.yml
roles/firmware/tasks/smithi/bmc.yml
roles/fog-server/tasks/main.yml
roles/public_facing/tasks/letsencrypt_nginx.yml
roles/rook/tasks/rook-recovery.yml
roles/testnode/tasks/cpan.yml
roles/testnode/tasks/ntp.yml
roles/users/tasks/filter_users.yml

Run Ansible's `--syntax-check` and `ansible-lint` on every PR and Git push.
Ignore some common `ansible-lint` errors so we can get to green quickly. We can re-evaluate this list later and perhaps fix some of them down the road.

github: add syntax and lint checks

---

tools/checkcerts.py

As it says on the tin.  paddles.front now support https.  Add it to the list of checked hosts.

tools/checkcerts.py: add paddles.front to list of checked hosts

---

roles/testnode/tasks/yum/repos.yml

https://github.com/ceph/ceph-cm-ansible/pull/731 removed the custom-made repo files that added mirrorlists; however, it also removed the side-effect of enabling the Power Tools repo (which is not enabled by default).  This adds a call to dnf config-manager to enable the repo, whatever its repo file name, on CentOS testnodes.
Fixes: https://tracker.ceph.com/issues/59678

testnode: Make sure PowerTools repo is enabled on CentOS

---

roles/testnode/tasks/yum/repos.yml

a candidate fix for https://tracker.ceph.com/issues/61648
i verified that the `dnf -y config-manager --set-enabled crb` command works against a fresh centos stream 9 install, but haven't tested the ansible changes themselves

testnode: replace 'powertools' with 'crb' for centos 9+

---

roles/common/tasks/rhel-entitlements.yml

We can't leave /etc/machine-id blank; it breaks things, one of which is the kernel install, which runs a postinstall script to update /boot/loader/entries, which does nothing (silently) if there's nothing in /etc/machine-id.  Since it can come from the dbus id, and does by default, and there's a command to generate the dbus id, generate both, dbus first.  This fixes the kernel postinstall. I don't know if there should be any correlation between machine-id and the subscription-manager/katello IDs.

common/tasks/rhel-entitlements.yml: regenerate machine-id

---

roles/testnode/vars/centos_8.yml
roles/testnode/vars/centos_9.yml

Fixes: https://tracker.ceph.com/issues/62227

centos8, centos9: install dbench package from epel instead of lab-extras

---

roles/testnode/vars/centos_9.yml

iozone is present in the newly-created lab-extras repo, for the same reasons it's in other CentOS configs

roles/testnode/vars/centos_9.yml: add lab-extras and iozone

---

roles/cobbler_profile/tasks/download_image.yml
roles/cobbler_profile/tasks/import_distro_image.yml

1) ansible's get_url moves from sha256 to checksum 2) fix 'registered' name (import -> imported) in import_distro_image

cobbler_profile: fix two bugs discovered while importing inktank-rescue

---

roles/testnode/vars/centos_9.yml

CentOS 8 had different .repo files for each major section (BaseOS, AppStream, etc.).  CentOS 9 has apparently moved to a single file, centos.repo.  This change 1) removes the management of separate repo files for BaseOS and AppStream, since those repos are included in centos.repo, and 2) stops using the perhaps-questionable single baseurl in favor of the default metalink/mirrors setup
There are errors occurring for teuthology tests on centos9 that may be related to this, with the errors of the form "<pkg> from <repo> does not belong to a distupgrade repository".  As near as I can tell, a "distupgrade repository" is one used only for upgrade, and I can't find information on how exactly it's indicated, so I don't know if this change will resolve the error or not.

Remove unnecessary duplicate repo definitions for centos9

---

roles/cobbler_profile/tasks/download_image.yml
roles/cobbler_profile/tasks/download_iso.yml
roles/pulpito/tasks/main.yml
roles/pulpito/tasks/setup_pulpito.yml
roles/testnode/tasks/resolvconf.yml

Fixes: https://tracker.ceph.com/issues/66106
get_md5 was removed in ansible 2.9: https://docs.ansible.com/ansible/2.8/modules/stat_module.html
Release notes for ansible 9 (or ansible-core 2.16): https://github.com/ansible-community/ansible-build-data/blob/0dee49ac8a7674153606ddc6432d4029eb20172d/9/CHANGELOG-v9.rst#L5195
Result: https://pulpito.ceph.com/vallariag-2024-05-20_05:57:34-rbd:nvmeof-main-distro-default-smithi/

Fix "Unsupported parameters for (stat) module: get_md5" 

---

tools/prep-fog-capture.yml

The mount module has moved; give it a full path.  Requires https://github.com/ceph/ceph-build/pull/2275 to allow the module to be found.  Tested manually.

prep-fog-capture.yml: mount -> ansible.posix.mount

---

roles/cobbler/templates/snippets/cephlab_packages_rhel

FOG capture requires dbus-uuidgen (in dbus-tools) and the presence of /var/lib/dbus (from dbus-daemon) to do the bug-avoidance dance for Satellite.  It's not clear that bug-avoidance dance is still necessary, but this is the minimal-investigation minimal-touch change to make the capture process work.

roles/cobbler/templates/snippets/cephlab_packages_rhel: add dbus pkgs

---

roles/testnode/vars/debian_7.yml
roles/testnode/vars/debian_8.yml
roles/testnode/vars/ubuntu.yml

We haven't done anything with tgt for over 10 years and tgt can interfere with setting up ceph-iscsi targets, resulting in "Could not create NetworkPortal in configFS" errors.

testnode: don't install tgt

---

roles/testnode/vars/apt_systems.yml
roles/testnode/vars/yum_systems.yml
roles/testnode/vars/zypper_systems.yml

As a follow up for commit 67a92953a5a2 ("testnode: don't install tgt"), explicitly remove tgt to cover the case of it already being there.  This also documents that we actively don't want tgt to be there.

testnode: remove tgt

---

roles/testnode/vars/apt_systems.yml
roles/testnode/vars/ubuntu.yml

Otherwise, because it's placed in ubuntu.yml, it resets packages_to_remove list defined in apt_systems.yml to just openmpi-common and commit 701d3594d220 ("testnode: remove tgt") doesn't take effect.
While at it, fix a typo in the comment -- it's mpich.

testnode: move removing openmpi-common to apt_systems.yml

---

tools/checkcerts.py

argparse can't do a nargs="*" optional arg *and* check for its presence; add a separate arg -E to send the email, and keep -e as an optional list of addressees.
Also add the full path and host where checkcerts.py is running.

checkcerts.py: actually fix "send email"

---

roles/grafana_agent/defaults/main.yml
roles/grafana_agent/files/grafana/customuseradd.te
roles/grafana_agent/tasks/main.yml
roles/grafana_agent/tasks/useradd-selinux.yml
testnodes.yml

This code creates a new ansible task in the grafana_agent role that configures a SELinux module on CentOS and RedHat systems which allows useradd command to access var_lib_t context files, that way we can avoid SELinux denials after the grafana installation on the teuthology-suite's executions.
Fixes: https://ibm.monday.com/boards/5591222586/pulses/8269716052
I have run a test with teuthology-suite command like this in order to verify if the module was working or not.
teuthology-suite -s smoke --ceph-repo ceph -c squid --suite-repo ceph -m smithi --subset 1/5 -p 50 -l 8 --force-priority --newest 10 --sha1 a8eeed19eb9ce9bdce3a02ea18f12005000c9146 /home/falcocer/ansible-branch.yml
Result before the module:
https://pulpito.ceph.com/falcocer-2025-02-17_21:50:23-smoke-squid-distro-default-smith …

Creating a selinux module to resolve selinux conflicts with grafana agent

---

roles/testnode/README.rst
roles/testnode/meta/main.yml
testnodes.yml

Snippet from ansible.log
```
TASK [grafana_agent : Gather facts on listening ports] *************************
skipping: [smithi116.front.sepia.ceph.com] => {"changed": false, "false_condition": "run_grafana_agent_role is defined and run_grafana_agent_role", "skip_reason": "Conditional result was False"}
```
https://pulpito.ceph.com/dgalloway-2025-03-03_22:29:15-smoke-squid-distro-default-smithi/
We'll define this at the machine type level in the secrets repos.

testnode: Run grafana_agent role optionally

---

roles/gateway/files/openvpn.logrotate
roles/gateway/files/openvpn_weekly_rotation
roles/gateway/tasks/logging.yml

The daily rotation was configured to keep daily logs for a week. A new script to manage weekly rotation and keep those logs for a year was generated to be put into /etc/cron.weekly
Fixes: https://ibm.monday.com/boards/5591222586/pulses/8354436354

OpenVPN logrotate configuration to keep the logs for a year.

---

roles/testnode/tasks/apt/repos.yml

The linked tracker above the custom repo removal task is from long before we had golden OS images (pre-FOG).

testnode: Remove needless tasks

---

tools/set-next-server.sh

Otherwise, the `linenum=` line gets two line numbers.

tools: Exclude `option host-name` from grep hostname in set-next-server
